name: "enroll_102_profile"
description: "wf enrollment 102 profile"
inputs:
  ASA_PROFILE1:
    description: "ASA Profile 1"
    required: true
  ASA_PROFILE2:
    description: "ASA Profile 2"
    required: true

runs:
  using: "composite"
  steps:
  - name: "Sleep for 10s"
    uses: juliangruber/sleep-action@v2.0.3
    with:
      time: 10s

  - name: "ACME Profiling - Test http://acme-srv/directory is accessible"
    run: docker run -i --rm --network acme curlimages/curl -f http://acme-srv/directory
    shell: bash

  - name: "ACME Profiling - Test if https://acme-srv/directory is accessible"
    run: docker run -i --rm --network acme curlimages/curl --insecure -f https://acme-srv/directory
    shell: bash

  - name: "ACME Profiling - 01 - Enroll lego with Profile 1"
    run: |
      sudo rm -rf lego/*
      docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego --tls-skip-verify -s https://acme-srv -a --email "lego@example.com" -d lego.acme --key-type rsa2048 --http run --profile "$ASA_PROFILE1"
      sudo openssl verify -CAfile cert-2.pem -untrusted cert-1.pem lego/certificates/lego.acme.crt
      # sudo openssl x509 -in lego/certificates/lego.acme.crt -text -noout
      sudo openssl x509 -in lego/certificates/lego.acme.crt -ext keyUsage -noout | grep "Digital Signature"
    env:
      ASA_PROFILE1: ${{ inputs.ASA_PROFILE1 }}
    shell: bash

  - name: "ACME Profiling - 02 - Enroll lego with Profile 2"
    run: |
      sudo rm -rf lego/*
      docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego --tls-skip-verify -s https://acme-srv -a --email "lego@example.com"  -d lego.acme --key-type rsa2048 --http run --profile "$ASA_PROFILE2"
      sudo openssl verify -CAfile cert-2.pem -untrusted cert-1.pem lego/certificates/lego.acme.crt
      # sudo openssl x509 -in lego/certificates/lego.acme.crt -text -noout
      sudo openssl x509 -in lego/certificates/lego.acme.crt -ext keyUsage -noout | grep "Key Encipherment, Data Encipherment"
    env:
      ASA_PROFILE2: ${{ inputs.ASA_PROFILE2 }}
    shell: bash
