name: "enroll_acmeprofile"
description: "enroll_acmeprofile‚"
inputs:
  DEPLOYMENT_TYPE:
    description: "Deployment type"
    required: true
    default: "rpm"
  HOSTNAME_SUFFIX:
    description: "Hostname suffix for the domain"
    required: true
    default: "-unknown"

runs:
  using: "composite"
  steps:
  - name: "Sleep for 5s"
    uses: juliangruber/sleep-action@v2.0.3
    with:
      time: 5s

  - name: "EAB - Test http://acme-srv/directory is accessible"
    run: docker run -i --rm --network acme curlimages/curl -f http://acme-srv/directory
    shell: bash

  - name: "EAB - Test if https://acme-srv/directory is accessible"
    run: docker run -i --rm --network acme curlimages/curl --insecure -f https://acme-srv/directory
    shell: bash

  - name: "Enroll lego"
    run: |
      echo $DOMAIN
      echo "Derived domain: $HOSTNAME_SUFFIX"
      sudo rm -rf lego/*
      docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego --tls-skip-verify -s https://acme-srv -a --email "lego@example.com" -d lego$HOSTNAME_SUFFIX.$DOMAIN --eab --kid $EAB_KID --hmac $EAB_EAB_HMAC_KEY --http run
      sudo openssl x509 -in lego/certificates/lego.acme.crt -text -noout
    shell: bash
    env:
      HOSTNAME_SUFFIX: ${{ inputs.HOSTNAME_SUFFIX }}

  - name: "Sleep for 5s"
    uses: juliangruber/sleep-action@v2.0.3
    with:
      time: 5s

