ignore:
  - "acme2certifier/share/skeletons/ca_handler/skeleton_ca_handler.py"
  - "acme2certifier/share/skeletons/eab_handler/skeleton_eab_handler.py"
  - "acme2certifier/share/skeletons/hooks/skeleton_hooks.py"
  - "docs/__init__.py"
  - "setup.py"
  - "test"
