---
apiVersion: v1
kind: Namespace
metadata:
  name: dnsmasq
---
apiVersion: v1
kind: Pod
metadata:
  name: dnsmasq
  namespace: dnsmasq
  labels:
    app: dns-masq
spec:
  hostname: dnsmasq
  automountServiceAccountToken: false
  containers:
    - name: dnsmasq
      image: gigantuar/dnsmasq:latest-amd64
      imagePullPolicy: Never
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
          ephemeral-storage: "64Mi"
        limits:
          memory: "128Mi"
          cpu: "200m"
          ephemeral-storage: "128Mi"
      volumeMounts:
        - mountPath: /etc/dnsmasq.conf
          name: dnscfg
          subPath: dnsmasq.conf
  volumes:
    - name: dnscfg
      hostPath:
        path: RUNNER_PATH/data
        type: Directory
