sonar.projectKey=grindsa_acme2certifier
sonar.organization=grindsa
sonar.python.coverage.reportPaths=coverage.xml
sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5,e6,e7,e8,e9,e10
sonar.issue.ignore.multicriteria.e1.ruleKey=githubactions:S7637
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.yml
# curl http
sonar.issue.ignore.multicriteria.e2.ruleKey=githubactions:S6573
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.yml
# glob fales positive
sonar.issue.ignore.multicriteria.e3.ruleKey=githubactions:S4830
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.yml
# python Calls should not be made to non-callable values
sonar.issue.ignore.multicriteria.e4.ruleKey=python:S5756
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.py
# long line in docker file
sonar.issue.ignore.multicriteria.e5.ruleKey=docker:S7020
sonar.issue.ignore.multicriteria.e5.resourceKey=**/Dockerfile
# usage of http
sonar.issue.ignore.multicriteria.e6.ruleKey=githubactions:S5332
sonar.issue.ignore.multicriteria.e6.resourceKey=**/*.yml
# non enforcement of tls
sonar.issue.ignore.multicriteria.e7.ruleKey=githubactions:S6506
sonar.issue.ignore.multicriteria.e7.resourceKey=**/*.yml
# pip installation Omitting "--only-binary :all:" can lead to the execution of setup scripts. Make sure it is safe here.
sonar.issue.ignore.multicriteria.e8.ruleKey=shell:S8541
sonar.issue.ignore.multicriteria.e8.resourceKey=**/*.yml
# pip installation Omitting "--only-binary :all:" can lead to the execution of setup scripts. Make sure it is safe here.
sonar.issue.ignore.multicriteria.e9.ruleKey=githubactions::S8541
sonar.issue.ignore.multicriteria.e9.resourceKey=**/*.yml
# pip installation Using dependencies without locking resolved versions is security-sensitive.
sonar.issue.ignore.multicriteria.e10.ruleKey= githubactions:S8544
sonar.issue.ignore.multicriteria.e10.resourceKey=**/*.yml


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=acme2certifier
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
