name: "maria_prep"
description: "bring up and configure mariadb instance"
inputs:
  NAME_SPACE:
    description: "Name space"
    required: true
    default: "acme"

runs:
  using: "composite"
  steps:
    - name: "Instanciate Mariadb"
      run: |
        # sudo mkdir -p data/mysql
        docker run --name mariadbsrv --network acme -e MARIADB_ROOT_PASSWORD=foobar -d mariadb
      shell: bash
      env:
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Sleep for 10s"
      uses: juliangruber/sleep-action@v2.0.3
      with:
        time: 10s

    - name: "Configure mariadb"
      working-directory: examples/Docker/
      run: |
        docker exec mariadbsrv mariadb -u root --password=foobar -e"CREATE DATABASE acme2certifier CHARACTER SET UTF8;"
        docker exec mariadbsrv mariadb -u root --password=foobar -e"GRANT ALL PRIVILEGES ON acme2certifier.* TO 'acme2certifier'@'%' IDENTIFIED BY '1mmSvDFl';"
        docker exec mariadbsrv mariadb -u root --password=foobar -e"FLUSH PRIVILEGES;"
      shell: bash

    - name: "Sleep for 5s"
      uses: juliangruber/sleep-action@v2.0.3
      with:
        time: 5s
