name: "Build RPM package"
description: "Build RPM package"
inputs:
  DB_HANDLER:
    description: "Database handler"
    required: true
    default: "wsgi"
  WEB_SRV:
    description: "Web server"
    required: true
    default: "apache2"
  DJANGO_DB:
    description: "Django database"
    required: false
  CONTAINER_BUILD:
    description: "Build container"
    required: true
    default: "true"

runs:
  using: "composite"
  steps:
    - name: "Setup environment"
      run: |
        docker network create acme
        sudo mkdir -p examples/Docker/data
        sudo cp .github/acme2certifier.pem examples/Docker/data/acme2certifier.pem
        sudo cp .github/acme2certifier_cert.pem examples/Docker/data/acme2certifier_cert.pem
        sudo cp .github/acme2certifier_key.pem examples/Docker/data/acme2certifier_key.pem
        if [ -z "$DJANGO_DB" ]; then
            sudo cp .github/django_settings.py examples/Docker/data/settings.py
        else
            sudo cp .github/django_settings_$DJANGO_DB.py examples/Docker/data/settings.py
        fi
      env:
        DJANGO_DB: ${{ inputs.DJANGO_DB }}
      shell: bash

    - name: "Build docker-compose (${{ inputs.WEB_SRV }}_${{ inputs.DB_HANDLER }})"
      if: inputs.CONTAINER_BUILD == 'true'
      uses: ./.github/actions/container_build
      with:
        WEB_SRV: ${{ inputs.WEB_SRV }}
        DB_HANDLER: ${{ inputs.DB_HANDLER }}

    - name: "Spin-up a2c instance (${{ inputs.WEB_SRV }}_${{ inputs.DB_HANDLER }})"
      if: inputs.CONTAINER_BUILD == 'true'
      working-directory: examples/Docker/
      run: |
          docker-compose up -d
      shell: bash