[libdefaults]
default_realm = NOTADEMO.NCLM.LOCAL
dns_lookup_kdc = false
dns_lookup_realm = false

[realms]
NOTADEMO.NCLM.LOCAL = {
    kdc = ec2amaz-ui0qfbn.notademo.nclm.local
    admin_server = ec2amaz-ui0qfbn.notademo.nclm.local
    default_domain = NOTADEMO.NCLM.LOCAL
}

[domain_realm]
.NOTADEMO.NCLM.LOCAL = NOTADEMO.NCLM.LOCAL
