name: "mssql_prep"
description: "bring up and configure mssql instance"
inputs:
  NAME_SPACE:
    description: "Name space"
    required: true
    default: "acme"
  INSTANCIATE:
    description: "Instanciate mssql"
    required: true
    default: "true"
  RH_VERSION:
    description: "Red Hat version"
    required: false
    default: "9"
  ROOT_PWD:
    description: "MSSQL root password"
    required: false
    default: "Mssqlpassw0rd"

runs:
  using: "composite"
  steps:
    - name: "Instanciate MSSQL"
      if: inputs.INSTANCIATE == 'true'
      run: |
        docker pull mcr.microsoft.com/mssql/server:2022-latest
        docker run --rm -d --network ${NAME_SPACE} -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=$ROOT_PWD"   -p 1433:1433 --name ms-sql --hostname ms-sql mcr.microsoft.com/mssql/server:2022-latest
      shell: bash
      env:
        NAME_SPACE: ${{ inputs.NAME_SPACE }}
        RH_VERSION: ${{ inputs.RH_VERSION }}
        ROOT_PWD: ${{ inputs.ROOT_PWD }}

    - name: "Sleep for 10s"
      if: inputs.INSTANCIATE == 'true'
      uses: juliangruber/sleep-action@v2.0.3
      with:
        time: 10s

    - name: "Configure mssql"
      working-directory: examples/Docker/
      run: |
        docker exec ms-sql /opt/mssql-tools18/bin/sqlcmd -No -S localhost -U SA -P $ROOT_PWD -Q "IF EXISTS (SELECT name FROM sys.databases WHERE name = 'acme2certifier') DROP DATABASE acme2certifier;"
        docker exec ms-sql /opt/mssql-tools18/bin/sqlcmd -No -S localhost -U SA -P $ROOT_PWD -Q "CREATE DATABASE acme2certifier;"
        docker exec ms-sql /opt/mssql-tools18/bin/sqlcmd -S localhost -No -U SA -P $ROOT_PWD -Q "CREATE LOGIN acme2certifier_user WITH PASSWORD = '$USER_PWD';"
        docker exec ms-sql /opt/mssql-tools18/bin/sqlcmd -S localhost -No -U SA -P $ROOT_PWD  -Q "USE acme2certifier; CREATE USER acme2certifier_user FOR LOGIN acme2certifier_user; ALTER ROLE db_owner ADD MEMBER acme2certifier_user;"
      shell: bash
      env:
        ROOT_PWD: ${{ inputs.ROOT_PWD }}
        USER_PWD: 1mmSvDFl
        RH_VERSION: ${{ inputs.RH_VERSION }}

    - name: "Sleep for 5s"
      uses: juliangruber/sleep-action@v2.0.3
      with:
        time: 5s
