name: "order_error_checking"
description: "EAB enroll with unknown credentials"
inputs:
  NAME_SPACE:
    description: "namespace"
    required: false
    default: "acme"
  DEPLOYMENT_TYPE:
    description: "Deployment type"
    required: false
    default: "container"
  ACME_SERVER:
    description: "ACME server hostname"
    required: false
    default: "acme-srv"
  HTTP_PORT:
    description: "ACME server HTTP port"
    required: false
    default: "80"
  HTTPS_PORT:
    description: "ACME server HTTPS port"
    required: false
    default: "443"
  ALMA_START:
    description: "Start alma container"
    required: true
    default: "true"

runs:
  using: "composite"
  steps:
    - name: "Test Registration without email"
      working-directory: acmeshell
      run: |
        cat <<EOT > commands.shell
        newAccount -contacts=foo.bar.local,
        EOT
      shell: bash

    - name: "Run acmeshell newAccount command to trigger error message"
      working-directory: acmeshell
      continue-on-error: true
      run: |
        docker exec alma bash -c '/acmeshell/acmeshell -directory http://acme-srv -postAsGet=true -printResponses -printRequests -in /acmeshell/commands.shell &> /acmeshell/acmeshell.enroll.log'
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Check acmeshell log for invalidContact error"
      working-directory: acmeshell
      run: |
        grep "urn:ietf:params:acme:error:malformed" acmeshell.enroll.log
      shell: bash

    - name: "Check a2c logs for malformed error"
      working-directory: examples/Docker/
      run: |
        if [ "$DEPLOYMENT_TYPE" == "container" ]; then
          docker compose logs | grep "{'status': 400, 'type': 'urn:ietf:params:acme:error:malformed', 'detail': 'Contact information is missing'}"
          sudo truncate -s 0 $(docker inspect --format='{{.LogPath}}' acme2certifier-acme-srv-1)
        elif [ "$DEPLOYMENT_TYPE" == "rpm" ]; then
          docker exec -i acme-srv tail -n 500 /var/log/messages | grep "{'status': 400, 'type': 'urn:ietf:params:acme:error:malformed', 'detail': 'Contact information is missing'}"
        fi
      shell: bash
      env:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}

    - name: "Test Registration with wrong email format"
      working-directory: acmeshell
      run: |
        cat <<EOT > commands.shell
        newAccount -contacts=foo.bar.local,
        EOT
      shell: bash

    - name: "Run acmeshell newAccount command to trigger error message"
      working-directory: acmeshell
      continue-on-error: true
      run: |
        docker exec alma bash -c '/acmeshell/acmeshell -directory http://acme-srv -postAsGet=true -printResponses -printRequests -autoregister=false --account="" -in /acmeshell/commands.shell &> /acmeshell/acmeshell.enroll.log'
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Check acmeshell log for invalidContact error"
      working-directory: acmeshell
      run: |
        grep "urn:ietf:params:acme:error:invalidContact" acmeshell.enroll.log
      shell: bash

    - name: "Check a2c logs for invalidContact error"
      working-directory: examples/Docker/
      run: |
        if [ "$DEPLOYMENT_TYPE" == "container" ]; then
          docker compose logs | grep "{'status': 400, 'type': 'urn:ietf:params:acme:error:invalidContact', 'detail': 'The provided contact URI was invalid: Invalid contact information'}"
          sudo truncate -s 0 $(docker inspect --format='{{.LogPath}}' acme2certifier-acme-srv-1)
        elif [ "$DEPLOYMENT_TYPE" == "rpm" ]; then
          docker exec -i acme-srv tail -n 500 /var/log/messages | grep "{'status': 400, 'type': 'urn:ietf:params:acme:error:invalidContact', 'detail': 'The provided contact URI was invalid: Invalid contact information'}"
        fi
      shell: bash
      env:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}

    - name: "Test Registration with correct email format"
      working-directory: acmeshell
      run: |
        rm -f acmeshell.enroll.log
        cat <<EOT > commands.shell
        newAccount -contacts=foo@bar.local,
        getAccount
        post -body='{"status":"deactivated"}' {{ account }}
        EOT
      shell: bash

    - name: "Run acmeshell newAccount command"
      working-directory: acmeshell
      continue-on-error: true
      run: |
        docker exec alma bash -c '/acmeshell/acmeshell -directory http://acme-srv -postAsGet=true -printResponses -printRequests -autoregister=false --account="" -in /acmeshell/commands.shell &> /acmeshell/acmeshell.enroll.log'
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Check acmeshell log"
      working-directory: acmeshell
      run: |
        grep "HTTP\/1.1 201 OK" acmeshell.enroll.log
        grep "{\"status\": \"valid\"" acmeshell.enroll.log
        grep "{\"status\": \"deactivated\"}" acmeshell.enroll.log
      shell: bash

    - name: "Check a2c logs"
      working-directory: examples/Docker/
      run: |
        if [ "$DEPLOYMENT_TYPE" == "container" ]; then
          docker compose logs | grep "Account.onlyreturnexisting() ended with: 200"
          docker compose logs | grep "Account._deactivate_account("
          sudo truncate -s 0 $(docker inspect --format='{{.LogPath}}' acme2certifier-acme-srv-1)
        elif [ "$DEPLOYMENT_TYPE" == "rpm" ]; then
          docker exec -i acme-srv tail -n 500 /var/log/messages | grep "Account.onlyreturnexisting() ended with: 200"
          docker exec -i acme-srv tail -n 500 /var/log/messages | grep "Account._deactivate_account("
        fi
      shell: bash
      env:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}

    - name: "Test registration without TOC agreement using a modifed acme.sh"
      continue-on-error: true
      id: acmeshfail01
      run: |
        docker exec alma bash -c 'grep regjson /root/.acme.sh/acme.sh'
        docker exec alma sed -i 's/termsOfServiceAgreed/foo/g' /root/.acme.sh/acme.sh
        docker exec alma bash -c 'grep regjson /root/.acme.sh/acme.sh'
        docker exec alma bash -c '/root/.acme.sh/acme.sh --register-account --server http://acme-srv --accountemail acme-sh@example.com'
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}

    - name: "check  result "
      if: ${{ steps.acmeshfail01.outcome != 'failure' }}
      run: |
        echo "acmeshfail outcome is ${{steps.acmeshfail01.outcome }}"
        exit 1
      shell: bash

    - name: "Check a2c logs"
      working-directory: examples/Docker/
      run: |
        if [ "$DEPLOYMENT_TYPE" == "container" ]; then
          docker compose logs | grep "no tos statement found."
          docker compose logs | grep "{'status': 403, 'type': 'urn:ietf:params:acme:error:userActionRequired', 'detail': 'termsofserviceagreed flag missing'}"
          sudo truncate -s 0 $(docker inspect --format='{{.LogPath}}' acme2certifier-acme-srv-1)
        elif [ "$DEPLOYMENT_TYPE" == "rpm" ]; then
          docker exec -i acme-srv tail -n 500 /var/log/messages | grep "no tos statement found."
          docker exec -i acme-srv tail -n 500 /var/log/messages | grep "{'status': 403, 'type': 'urn:ietf:params:acme:error:userActionRequired', 'detail': 'termsofserviceagreed flag missing'}"
        fi
      shell: bash
      env:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}

    - name: "Test registration with TOC agreement false using a modifed acme.sh"
      id: acmeshfail02
      continue-on-error: true
      run: |
        docker exec alma bash -c 'cp /root/.acme.sh/acme.sh.bup /root/.acme.sh/acme.sh'
        docker exec alma bash -c 'grep regjson /root/.acme.sh/acme.sh'
        docker exec alma sed -i 's/\\"termsOfServiceAgreed\\": true/\\"termsOfServiceAgreed\\": false/g' /root/.acme.sh/acme.sh
        docker exec alma bash -c 'grep regjson /root/.acme.sh/acme.sh'
        docker exec alma bash -c '/root/.acme.sh/acme.sh --register-account --server http://acme-srv --accountemail acme-sh@example.com'
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}

    - name: "check  result "
      if: ${{ steps.acmeshfail02.outcome != 'failure' }}
      run: |
        echo "acmeshfail outcome is ${{steps.acmeshfail02.outcome }}"
        exit 1
      shell: bash

    - name: "Check a2c logs"
      working-directory: examples/Docker/
      run: |
        if [ "$DEPLOYMENT_TYPE" == "container" ]; then
          docker compose logs | grep "tos:False"
          docker compose logs | grep "{'status': 403, 'type': 'urn:ietf:params:acme:error:userActionRequired', 'detail': 'Terms of service must be agreed'}"
          sudo truncate -s 0 $(docker inspect --format='{{.LogPath}}' acme2certifier-acme-srv-1)
        elif [ "$DEPLOYMENT_TYPE" == "rpm" ]; then
          docker exec -i acme-srv tail -n 500 /var/log/messages | grep "tos:False"
          docker exec -i acme-srv tail -n 500 /var/log/messages | grep "{'status': 403, 'type': 'urn:ietf:params:acme:error:userActionRequired', 'detail': 'Terms of service must be agreed'}"
        fi
      shell: bash
      env:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}


    - name: "Update account information"
      working-directory: acmeshell
      run: |
        rm -f acmeshell.enroll.log
        cat <<EOT > commands.shell
        newAccount -contacts=foo@bar.local,
        post -body='{"contact":["mailto:new@example.com"]}' {{ account }}
        EOT
      shell: bash

    - name: "Run acmeshell newAccount command"
      working-directory: acmeshell
      continue-on-error: true
      run: |
        docker exec alma bash -c '/acmeshell/acmeshell -directory http://acme-srv -postAsGet=true -printResponses -printRequests -autoregister=false --account="" -in /acmeshell/commands.shell &> /acmeshell/acmeshell.enroll.log'
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Check acmeshell log"
      working-directory: acmeshell
      run: |
        grep "HTTP\/1.1 201 OK" acmeshell.enroll.log
        grep "HTTP\/1.1 200 Created" acmeshell.enroll.log
        grep "\"contact\": \[\"mailto:new@example.com\"\], \"createdAt\":" acmeshell.enroll.log
      shell: bash

    - name: "Check a2c logs"
      working-directory: examples/Docker/
      run: |
        if [ "$DEPLOYMENT_TYPE" == "container" ]; then
          docker compose logs | grep "validate: new@example.com result: True"
          docker compose logs | grep "DBStore.account_update("
          sudo truncate -s 0 $(docker inspect --format='{{.LogPath}}' acme2certifier-acme-srv-1)
        elif [ "$DEPLOYMENT_TYPE" == "rpm" ]; then
          docker exec -i acme-srv tail -n 500 /var/log/messages | grep "validate: new@example.com result: True"
          docker exec -i acme-srv tail -n 500 /var/log/messages | grep "DBStore.account_update("
        fi
      shell: bash
      env:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}

    - name: "Unknown account request"
      working-directory: acmeshell
      run: |
        rm -f acmeshell.enroll.log
        cat <<EOT > commands.shell
        newAccount -contacts=foo@bar.local,
        post -body='{"foo": "bar"}' {{ account }}
        EOT
      shell: bash

    - name: "Run acmeshell newAccount command"
      working-directory: acmeshell
      continue-on-error: true
      run: |
        docker exec alma bash -c '/acmeshell/acmeshell -directory http://acme-srv -postAsGet=true -printResponses -printRequests -autoregister=false --account="" -in /acmeshell/commands.shell &> /acmeshell/acmeshell.enroll.log'
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Check acmeshell log"
      working-directory: acmeshell
      run: |
        grep "{\"status\": 400, \"type\": \"urn:ietf:params:acme:error:malformed\", \"detail\": \"Unknown request\"}" acmeshell.enroll.log
      shell: bash

    - name: "Check a2c logs"
      working-directory: examples/Docker/
      run: |
        if [ "$DEPLOYMENT_TYPE" == "container" ]; then
          docker compose logs | grep "Error.acme_errormessage(urn:ietf:params:acme:error:malformed)"
          sudo truncate -s 0 $(docker inspect --format='{{.LogPath}}' acme2certifier-acme-srv-1)
        elif [ "$DEPLOYMENT_TYPE" == "rpm" ]; then
          docker exec -i acme-srv tail -n 500 /var/log/messages | grep "Error.acme_errormessage(urn:ietf:params:acme:error:malformed)"
        fi
      shell: bash
      env:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}

    - name: "wrong status update"
      working-directory: acmeshell
      run: |
        rm -f acmeshell.enroll.log
        cat <<EOT > commands.shell
        newAccount -contacts=foo@bar.local,
        post -body='{"status":"valid"}' {{ account }}
        EOT
      shell: bash

    - name: "Run acmeshell newAccount command"
      working-directory: acmeshell
      continue-on-error: true
      run: |
        docker exec alma bash -c '/acmeshell/acmeshell -directory http://acme-srv -postAsGet=true -printResponses -printRequests -autoregister=false --account="" -in /acmeshell/commands.shell &> /acmeshell/acmeshell.enroll.log'
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Check acmeshell log"
      working-directory: acmeshell
      run: |
        grep "{\"status\": 400, \"type\": \"urn:ietf:params:acme:error:malformed\", \"detail\": \"Invalid status for deactivation\"}" acmeshell.enroll.log
      shell: bash

    - name: "Check a2c logs"
      working-directory: examples/Docker/
      run: |
        if [ "$DEPLOYMENT_TYPE" == "container" ]; then
          docker compose logs | grep "Error.acme_errormessage(urn:ietf:params:acme:error:malformed)"
          sudo truncate -s 0 $(docker inspect --format='{{.LogPath}}' acme2certifier-acme-srv-1)
        elif [ "$DEPLOYMENT_TYPE" == "rpm" ]; then
          docker exec -i acme-srv tail -n 500 /var/log/messages | grep "Error.acme_errormessage(urn:ietf:params:acme:error:malformed)"
        fi
      shell: bash
      env:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}

    - name: "Key Rollover"
      working-directory: acmeshell
      run: |
        rm -f acmeshell.enroll.log
        cat <<EOT > commands.shell
        newAccount -contacts=foo@bar.local,
        newKey -id=replacement.account.key
        keyRollover -keyID=replacement.account.key
        EOT
      shell: bash

    - name: "Run acmeshell newAccount command"
      working-directory: acmeshell
      continue-on-error: true
      run: |
        docker exec alma bash -c '/acmeshell/acmeshell -directory http://acme-srv -postAsGet=true -printResponses -printRequests -autoregister=false --account="" -in /acmeshell/commands.shell &> /acmeshell/acmeshell.enroll.log'
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Check acmeshell log"
      working-directory: acmeshell
      run: |
        cat acmeshell.enroll.log
        grep "Rollover for" acmeshell.enroll.log | grep "completed"
      shell: bash

    - name: "Check a2c logs"
      working-directory: examples/Docker/
      run: |
        if [ "$DEPLOYMENT_TYPE" == "container" ]; then
          docker compose logs | grep "Account._rollover_account_key("
          docker compose logs | grep "Account._validate_key_change("
          sudo truncate -s 0 $(docker inspect --format='{{.LogPath}}' acme2certifier-acme-srv-1)
        elif [ "$DEPLOYMENT_TYPE" == "rpm" ]; then
          docker exec -i acme-srv tail -n 500 /var/log/messages | grep "Account._rollover_account_key("
          docker exec -i acme-srv tail -n 500 /var/log/messages | grep "Account._validate_key_change("
        fi
      shell: bash
      env:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}