name: "account_error_checking"
description: "EAB enroll with unknown credentials"
inputs:
  NAME_SPACE:
    description: "namespace"
    required: false
    default: "acme"
  DEPLOYMENT_TYPE:
    description: "Deployment type"
    required: false
    default: "container"
  ACME_SERVER:
    description: "ACME server hostname"
    required: false
    default: "acme-srv"
  HTTP_PORT:
    description: "ACME server HTTP port"
    required: false
    default: "80"
  HTTPS_PORT:
    description: "ACME server HTTPS port"
    required: false
    default: "443"
  ALMA_START:
    description: "Start alma container"
    required: true
    default: "true"

runs:
  using: "composite"
  steps:
    - name: "Test Registration without email"
      working-directory: acmeshell
      run: |
        cat <<EOT > commands.shell
        newAccount -contacts=foo.bar.local,
        EOT
      shell: bash

    - name: "Run acmeshell newAccount command to trigger error message"
      working-directory: acmeshell
      continue-on-error: true
      run: |
        docker exec alma bash -c "/acmeshell/acmeshell -directory http://$ACME_SERVER -postAsGet=true -printResponses -printRequests -in /acmeshell/commands.shell &> /acmeshell/acmeshell.enroll.log"
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Check acmeshell log for invalidContact error"
      working-directory: acmeshell
      run: |
        cat acmeshell.enroll.log
        grep "urn:ietf:params:acme:error:malformed" acmeshell.enroll.log
      shell: bash

    - name: "Check a2c logs for malformed error"
      uses: ./.github/actions/logs_assert
      with:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        COMPOSE_SERVICE: ${{ inputs.ACME_SERVER }}
        PATTERN: "{'status': 400, 'type': 'urn:ietf:params:acme:error:malformed', 'detail': 'Contact information is missing'}"

    - name: "Test Registration with wrong email format"
      working-directory: acmeshell
      run: |
        cat <<EOT > commands.shell
        newAccount -contacts=foo.bar.local,
        EOT
      shell: bash

    - name: "Run acmeshell newAccount command to trigger error message"
      working-directory: acmeshell
      continue-on-error: true
      run: |
        docker exec alma bash -c "/acmeshell/acmeshell -directory http://$ACME_SERVER -postAsGet=true -printResponses -printRequests -autoregister=false --account=\"\" -in /acmeshell/commands.shell &> /acmeshell/acmeshell.enroll.log"
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Check acmeshell log for invalidContact error"
      working-directory: acmeshell
      run: |
        grep "urn:ietf:params:acme:error:invalidContact" acmeshell.enroll.log
      shell: bash

    - name: "Check a2c logs for invalidContact error"
      uses: ./.github/actions/logs_assert
      with:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        COMPOSE_SERVICE: ${{ inputs.ACME_SERVER }}
        PATTERN: "{'status': 400, 'type': 'urn:ietf:params:acme:error:invalidContact', 'detail': 'The provided contact URI was invalid: Invalid contact information'}"

    - name: "Test Registration with correct email format"
      working-directory: acmeshell
      run: |
        rm -f acmeshell.enroll.log
        cat <<EOT > commands.shell
        newAccount -contacts=foo@bar.local,
        getAccount
        post -body='{"status":"deactivated"}' {{ account }}
        EOT
      shell: bash

    - name: "Run acmeshell newAccount command"
      working-directory: acmeshell
      continue-on-error: true
      run: |
        docker exec alma bash -c "/acmeshell/acmeshell -directory http://$ACME_SERVER -postAsGet=true -printResponses -printRequests -autoregister=false --account=\"\" -in /acmeshell/commands.shell &> /acmeshell/acmeshell.enroll.log"
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Check acmeshell log"
      working-directory: acmeshell
      run: |
        # cat acmeshell.enroll.log
        grep "\"status\": \"valid\"" acmeshell.enroll.log
        grep "\"status\": \"deactivated\"" acmeshell.enroll.log
      shell: bash

    - name: "Check a2c logs - onlyreturnexisting"
      uses: ./.github/actions/logs_assert
      with:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        COMPOSE_SERVICE: ${{ inputs.ACME_SERVER }}
        PATTERN: "Account.onlyreturnexisting() ended with: 200"
        FLUSH: "false"

    - name: "Check a2c logs - deactivate_account"
      uses: ./.github/actions/logs_assert
      with:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        COMPOSE_SERVICE: ${{ inputs.ACME_SERVER }}
        PATTERN: "Account._deactivate_account("
        FLUSH: "true"

    - name: "Test registration without TOC agreement using a modifed acme.sh"
      continue-on-error: true
      id: acmeshfail01
      run: |
        docker exec alma bash -c "grep regjson /root/.acme.sh/acme.sh"
        docker exec alma sed -i 's/termsOfServiceAgreed/foo/g' /root/.acme.sh/acme.sh
        docker exec alma bash -c "grep regjson /root/.acme.sh/acme.sh"
        docker exec alma bash -c "/root/.acme.sh/acme.sh --register-account --server http://$ACME_SERVER --accountemail acme-sh@example.com"
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}

    - name: "check  result "
      if: ${{ steps.acmeshfail01.outcome != 'failure' }}
      run: |
        echo "acmeshfail outcome is ${{steps.acmeshfail01.outcome }}"
        exit 1
      shell: bash

    - name: "Check a2c logs - no tos statement"
      uses: ./.github/actions/logs_assert
      with:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        COMPOSE_SERVICE: ${{ inputs.ACME_SERVER }}
        PATTERN: "no tos statement found."
        FLUSH: "false"

    - name: "Check a2c logs - userActionRequired tos missing"
      uses: ./.github/actions/logs_assert
      with:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        COMPOSE_SERVICE: ${{ inputs.ACME_SERVER }}
        PATTERN: "{'status': 403, 'type': 'urn:ietf:params:acme:error:userActionRequired', 'detail': 'termsofserviceagreed flag missing'}"
        FLUSH: "true"

    - name: "Test registration with TOC agreement false using a modifed acme.sh"
      id: acmeshfail02
      continue-on-error: true
      run: |
        docker exec alma bash -c "cp /root/.acme.sh/acme.sh.bup /root/.acme.sh/acme.sh"
        docker exec alma bash -c "grep regjson /root/.acme.sh/acme.sh"
        docker exec alma sed -i 's/\\"termsOfServiceAgreed\\": true/\\"termsOfServiceAgreed\\": false/g' /root/.acme.sh/acme.sh
        docker exec alma bash -c "grep regjson /root/.acme.sh/acme.sh"
        docker exec alma bash -c "/root/.acme.sh/acme.sh --register-account --server http://$ACME_SERVER --accountemail acme-sh@example.com"
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}

    - name: "check  result "
      if: ${{ steps.acmeshfail02.outcome != 'failure' }}
      run: |
        echo "acmeshfail outcome is ${{steps.acmeshfail02.outcome }}"
        exit 1
      shell: bash

    - name: "Check a2c logs - tos:False"
      uses: ./.github/actions/logs_assert
      with:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        COMPOSE_SERVICE: ${{ inputs.ACME_SERVER }}
        PATTERN: "tos:False"
        FLUSH: "false"

    - name: "Check a2c logs - Terms of service must be agreed"
      uses: ./.github/actions/logs_assert
      with:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        COMPOSE_SERVICE: ${{ inputs.ACME_SERVER }}
        PATTERN: "{'status': 403, 'type': 'urn:ietf:params:acme:error:userActionRequired', 'detail': 'Terms of service must be agreed'}"
        FLUSH: "true"

    - name: "Update account information"
      working-directory: acmeshell
      run: |
        rm -f acmeshell.enroll.log
        cat <<EOT > commands.shell
        newAccount -contacts=foo@bar.local,
        post -body='{"contact":["mailto:new@example.com"]}' {{ account }}
        EOT
      shell: bash

    - name: "Run acmeshell newAccount command"
      working-directory: acmeshell
      continue-on-error: true
      run: |
        docker exec alma bash -c "/acmeshell/acmeshell -directory http://$ACME_SERVER -postAsGet=true -printResponses -printRequests -autoregister=false --account=\"\" -in /acmeshell/commands.shell &> /acmeshell/acmeshell.enroll.log"
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Check acmeshell log"
      working-directory: acmeshell
      run: |
        # grep "HTTP\/1.1 201 OK" acmeshell.enroll.log
        # grep "HTTP\/1.1 200 Created" acmeshell.enroll.log
        # grep "\"contact\": \[\"mailto:new@example.com\"\], \"createdAt\":" acmeshell.enroll.log
        grep "mailto:new@example.com" acmeshell.enroll.log
      shell: bash

    - name: "Check a2c logs - validate email"
      uses: ./.github/actions/logs_assert
      with:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        COMPOSE_SERVICE: ${{ inputs.ACME_SERVER }}
        PATTERN: "validate: new@example.com result: True"
        FLUSH: "false"

    - name: "Check a2c logs - account_update"
      uses: ./.github/actions/logs_assert
      with:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        COMPOSE_SERVICE: ${{ inputs.ACME_SERVER }}
        PATTERN: "DBStore.account_update("
        FLUSH: "true"

    - name: "Unknown account request"
      working-directory: acmeshell
      run: |
        rm -f acmeshell.enroll.log
        cat <<EOT > commands.shell
        newAccount -contacts=foo@bar.local,
        post -body='{"foo": "bar"}' {{ account }}
        EOT
      shell: bash

    - name: "Run acmeshell newAccount command"
      working-directory: acmeshell
      continue-on-error: true
      run: |
        docker exec alma bash -c "/acmeshell/acmeshell -directory http://$ACME_SERVER -postAsGet=true -printResponses -printRequests -autoregister=false --account=\"\" -in /acmeshell/commands.shell &> /acmeshell/acmeshell.enroll.log"
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Check acmeshell log"
      working-directory: acmeshell
      run: |
        grep "\"status\": 400," acmeshell.enroll.log
        grep "\"type\": \"urn:ietf:params:acme:error:malformed\"," acmeshell.enroll.log
        grep "\"detail\": \"Unknown request\"" acmeshell.enroll.log
      shell: bash

    - name: "Check a2c logs"
      uses: ./.github/actions/logs_assert
      with:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        COMPOSE_SERVICE: ${{ inputs.ACME_SERVER }}
        PATTERN: "Error.acme_errormessage(urn:ietf:params:acme:error:malformed)"

    - name: "wrong status update"
      working-directory: acmeshell
      run: |
        rm -f acmeshell.enroll.log
        cat <<EOT > commands.shell
        newAccount -contacts=foo@bar.local,
        post -body='{"status":"valid"}' {{ account }}
        EOT
      shell: bash

    - name: "Run acmeshell newAccount command"
      working-directory: acmeshell
      continue-on-error: true
      run: |
        docker exec alma bash -c "/acmeshell/acmeshell -directory http://$ACME_SERVER -postAsGet=true -printResponses -printRequests -autoregister=false --account=\"\" -in /acmeshell/commands.shell &> /acmeshell/acmeshell.enroll.log"
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Check acmeshell log"
      working-directory: acmeshell
      run: |
        grep "\"status\": 400," acmeshell.enroll.log
        grep "\"type\": \"urn:ietf:params:acme:error:malformed\"," acmeshell.enroll.log
        grep "\"detail\": \"Invalid status for deactivation\"" acmeshell.enroll.log
      shell: bash

    - name: "Check a2c logs"
      uses: ./.github/actions/logs_assert
      with:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        COMPOSE_SERVICE: ${{ inputs.ACME_SERVER }}
        PATTERN: "Error.acme_errormessage(urn:ietf:params:acme:error:malformed)"

    - name: "Key Rollover"
      working-directory: acmeshell
      run: |
        rm -f acmeshell.enroll.log
        cat <<EOT > commands.shell
        newAccount -contacts=foo@bar.local,
        newKey -id=replacement.account.key
        keyRollover -keyID=replacement.account.key
        EOT
      shell: bash

    - name: "Run acmeshell newAccount command"
      working-directory: acmeshell
      continue-on-error: true
      run: |
        docker exec alma bash -c "/acmeshell/acmeshell -directory http://$ACME_SERVER -postAsGet=true -printResponses -printRequests -autoregister=false --account=\"\" -in /acmeshell/commands.shell &> /acmeshell/acmeshell.enroll.log"
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Check acmeshell log"
      working-directory: acmeshell
      run: |
        grep "Rollover for" acmeshell.enroll.log | grep "completed"
      shell: bash

    - name: "Check a2c logs - rollover_account_key"
      uses: ./.github/actions/logs_assert
      with:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        COMPOSE_SERVICE: ${{ inputs.ACME_SERVER }}
        PATTERN: "Account._rollover_account_key("
        FLUSH: "false"

    - name: "Check a2c logs - validate_key_change"
      uses: ./.github/actions/logs_assert
      with:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        COMPOSE_SERVICE: ${{ inputs.ACME_SERVER }}
        PATTERN: "Account._validate_key_change("
        FLUSH: "true"

    - name: "Account query"
      working-directory: acmeshell
      run: |
        rm -f acmeshell.enroll.log
        cat <<EOT > commands.shell
        newAccount -contacts=foo@bar.local,
        post -body='{}' {{ account }}
        EOT
      shell: bash

    - name: "Run acmeshell newAccount command"
      working-directory: acmeshell
      continue-on-error: true
      run: |
        docker exec alma bash -c "/acmeshell/acmeshell -directory http://$ACME_SERVER -postAsGet=true -printResponses -printRequests -autoregister=false --account=\"\" -in /acmeshell/commands.shell &> /acmeshell/acmeshell.enroll.log"
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}

    - name: "Check acmeshell log"
      working-directory: acmeshell
      run: |
        ACCOUNT_ID=$(grep -oP 'Created account with ID "http://[^/]+/acme/acct/\K[^"]+' acmeshell.enroll.log | uniq)
        grep "Location: http://$ACME_SERVER/acme/acct/$ACCOUNT_ID" acmeshell.enroll.log
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
