name: "tunnel_setup"
description: "tunnel_setup"
inputs:
  WCCE_SSH_ACCESS_KEY:
    description: "SSH access key"
    required: true
  WCCE_SSH_KNOWN_HOSTS:
    description: "SSH known hosts"
    required: true
  WCCE_SSH_USER:
    description: "SSH user"
    required: true
  WCCE_SSH_HOST:
    description: "SSH host"
    required: true
  WCCE_SSH_PORT:
    description: "SSH port"
    required: true
  NAME_SPACE:
    description: "namespace"
    required: true
    default: "acme"
  NCM_API_HOST:
    description: "NCM API host"
    required: true
  NCM_API_USER:
    description: "NCM API user"
    required: true
  NCM_API_PASSWORD:
    description: "NCM API password"
    required: true
runs:
  using: "composite"
  steps:
  - name: "Prepare ssh environment on ramdisk "
    run: |
      sudo mkdir -p /tmp/rd
      sudo mount -t tmpfs -o size=5M none /tmp/rd
      sudo echo "$SSH_KEY" > /tmp/rd/ak.tmp
      sudo chmod 600 /tmp/rd/ak.tmp
      sudo echo "$KNOWN_HOSTS" > /tmp/rd/known_hosts
    env:
      SSH_KEY: ${{ inputs.WCCE_SSH_ACCESS_KEY }}
      KNOWN_HOSTS: ${{ inputs.WCCE_SSH_KNOWN_HOSTS }}
    shell: bash

  - name: "Setup ssh forwarder"
    run: |
        docker run -d --rm --network $NAME_SPACE --name=forwarder  -e "MAPPINGS=8084:127.0.0.1:8084" -e "SSH_HOST=$SSH_HOST" -e "SSH_PORT=$SSH_PORT" -e "SSH_USER=$SSH_USER" -p 8080:8084 -v "/tmp/rd/ak.tmp:/ssh_key:ro" davidlor/ssh-port-forward-client:dev
    env:
      SSH_USER: ${{ inputs.WCCE_SSH_USER }}
      SSH_HOST: ${{ inputs.WCCE_SSH_HOST }}
      SSH_PORT: ${{ inputs.WCCE_SSH_PORT }}
      NAME_SPACE: ${{ inputs.NAME_SPACE }}
      NCM_API_HOST: ${{ inputs.NCM_API_HOST }}
    shell: bash

  - name: "Sleep for 5s"
    uses: juliangruber/sleep-action@v2.0.3
    with:
      time: 5s

  - name: "Test conection to mscertsrv via ssh tunnel"
    run: |
      docker run -i --rm --network $NAME_SPACE curlimages/curl --insecure https://$NCM_API_USER:$NCM_API_PASSWORD@forwarder.acme:8084
    env:
      NCM_API_HOST: ${{ inputs.NCM_API_HOST }}
      NAME_SPACE: ${{ inputs.NAME_SPACE }}
      NCM_API_USER: ${{ inputs.NCM_API_USER }}
      NCM_API_PASSWORD: ${{ inputs.NCM_API_PASSWORD }}
    shell: bash
