name: "Build Container"
description: "Build Container"
inputs:
  DB_HANDLER:
    description: "Database handler"
    required: true
    default: "wsgi"
  WEB_SRV:
    description: "Web server"
    required: true
    default: "apache2"

runs:
  using: "composite"
  steps:
    - name: "Build docker-compose (${{ inputs.WEB_SRV }}_${{ inputs.DB_HANDLER }})"
      working-directory: examples/Docker/
      run: |
        sudo apt-get install -y docker-compose
        sed -i "s/wsgi/$DB_HANDLER/g" .env
        sed -i "s/apache2/$WEB_SRV/g" .env
        # cat .env
        docker-compose upbuild
      shell: bash
      env:
        WEB_SRV: ${{ inputs.WEB_SRV }}
        DB_HANDLER: ${{ inputs.DB_HANDLER }}
