# Generated by Django 6.0.7 on 2026-07-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acme_srv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housekeeping",
            name="value",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
