name: "eab_enroll_wo_credentials_success"
description: "EAB registration without credentials should succeed"
inputs:
  NAME_SPACE:
    description: "namespace"
    required: false
    default: "acme"
  ACME_SERVER:
    description: "ACME server hostname"
    required: false
    default: "acme-srv"
  HTTP_PORT:
    description: "ACME server HTTP port"
    required: false
    default: "80"

runs:
  using: "composite"
  steps:
    - name: "Sleep for 10s"
      uses: juliangruber/sleep-action@v2.0.4
      with:
        time: 10s

    - name: "Test http://acme-srv/directory is accessible"
      run: docker run -i --rm --network "$NAME_SPACE" curlimages/curl -f "http://$ACME_SERVER:$HTTP_PORT/directory"
      shell: bash
      env:
        NAME_SPACE: ${{ inputs.NAME_SPACE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        HTTP_PORT: ${{ inputs.HTTP_PORT }}

    - name: "acme.sh - Registration without credentials should succeed"
      run: |
        docker run --rm -i --network "$NAME_SPACE" --name=acme-sh neilpang/acme.sh:latest --register-account --server "http://$ACME_SERVER:$HTTP_PORT" --accountemail 'acme-sh-no-eab@example.com' --debug 2
      shell: bash
      env:
        NAME_SPACE: ${{ inputs.NAME_SPACE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        HTTP_PORT: ${{ inputs.HTTP_PORT }}

    - name: "certbot - Registration without credentials should succeed"
      run: |
        docker run -i --rm --name certbot --network "$NAME_SPACE" certbot/certbot register --agree-tos -m 'certbot-no-eab@example.com' --server "http://$ACME_SERVER:$HTTP_PORT" --no-eff-email
      shell: bash
      env:
        NAME_SPACE: ${{ inputs.NAME_SPACE }}
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        HTTP_PORT: ${{ inputs.HTTP_PORT }}
