name: "Cleanup after testing upgrade"
description: "Cleanup"

runs:
  using: "composite"
  steps:

    - name: "Cleanup"
      run: |
        if [ -d /var/www/acme2certifier/volume/migrations ]
        then
            echo "delete migration directory" >> /proc/1/fd/1
            rm -rf /var/www/acme2certifier/acme_srv/migrations
        fi
        if [ -d /var/www/acme2certifier/volume/db.sqlite3 ]
        then
            echo "delete db.sqlite3" >> /proc/1/fd/1
            rm -rf /var/www/acme2certifier/volume/db.sqlite3
        fi
        if [ -d /var/www/acme2certifier/volume/acme_srv.db ]
        then
            echo "delete db.sqlite3" >> /proc/1/fd/1
            rm -rf /var/www/acme2certifier/volume/acme_srv.db
        fi
      shell: bash


