name: "Cleanup after testing upgrade"
description: "Cleanup"

runs:
  using: "composite"
  steps:

    - name: "Cleanup"
      run: |
        if [ -d $(pwd)/data/migrations ]
        then
            echo "delete migration directory" >> /proc/1/fd/1
            rm -rf $(pwd)/data/migrations
        fi
        if [ -e $(pwd)/data/db.sqlite3 ]
        then
            echo "delete db.sqlite3" >> /proc/1/fd/1
            rm -rf $(pwd)/data/db.sqlite3
        fi
        if [ -e $(pwd)/data/acme_srv.db ]
        then
            echo "delete acme_srv.db" >> /proc/1/fd/1
            rm -rf $(pwd)/data/acme_srv.db
        fi
        ls -la $(pwd)/data/
      shell: bash


