name: "prevalidation tests"
description: "Test prevalidation feature - enroll acme clients against acme-srv using lego"
inputs:
  ACME_SERVER:
    description: "ACME server URL"
    required: true
    default: "acme-srv"
  CA_PATH:
    description: "Path to CA certificates"
    required: false
    default: "examples/Docker/data/acme_ca/"
  NAME_SPACE:
    description: "Namespace where acme-srv is deployed"
    required: false
    default: "acme"
  PREVALIDATED:
    description: "Whether to use prevalidation or not"
    required: false
    default: "both"

runs:
  using: "composite"
  steps:

    - name: "Sleep for 10s"
      uses: grindsa/sleep-action@master
      with:
        time: 10s

    - name: "Create lego folder"
      run: |
        rm -rf lego/*
        mkdir -p lego
        sudo truncate -s 0 $(docker inspect --format='{{.LogPath}}' acme2certifier-acme-srv-1)
      shell: bash

    - name: "Test http://acme-srv/directory is accessible"
      run: docker run -i --rm --network acme curlimages/curl -f http://$ACME_SERVER/directory
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}

    - name: "Test if https://acme-srv/directory is accessible"
      run: docker run -i --rm --network acme curlimages/curl --insecure -f https://$ACME_SERVER/directory
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}

    - name: "Enroll lego"
      if: ${{ inputs.PREVALIDATED == 'both' }}
      run: |
        docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network $NAME_SPACE goacme/lego --tls-skip-verify -s https://$ACME_SERVER -a --email "lego@example.com" -d lego.acme -d lego.foo.local -d 172.0.0.1 -d 10.0.0.1 --http run
      shell: bash
      env:
        ACME_SERVER: ${{ inputs.ACME_SERVER }}
        CA_PATH: ${{ inputs.CA_PATH }}
        NAME_SPACE: ${{ inputs.NAME_SPACE }}

    - name: "Check logs "
      if: ${{ inputs.PREVALIDATED == 'both' }}
      working-directory: examples/Docker/
      run: |
        if [ "$DEPLOYMENT_TYPE" == "container" ]; then
          echo "container deployment"
          docker compose logs | grep "enabling dryrun mode for profile: dry-run"
          sudo truncate -s 0 $(docker inspect --format='{{.LogPath}}' acme2certifier-acme-srv-1)
        elif [ "$DEPLOYMENT_TYPE" == "rpm" ]; then
          docker exec -i acme-srv tail -n 700 /var/log/messages | grep "enabling dryrun mode for profile: dry-run"
        fi
      shell: bash
      env:
        DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}