name: CA-Handler Tests - Insta ASA CA (deb)
on:
  workflow_call:
    inputs:
      run_id:
        description: Producer workflow run ID
        type: string
        required: true

permissions: {}

jobs:
  test-deb:
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        websrv: ['apache2', 'nginx']
        mode: ['wsgi', 'django']

    steps:
      - name: "checkout GIT"
        uses: actions/checkout@v7

      - name: "Channel setup"
        uses: ./.github/actions/channel_deb_setup
        with:
          RUN_ID: ${{ inputs.run_id }}
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}
          DJANGO_DB: ${{ matrix.mode == 'django' && 'psql' || '' }}

      - name: "Parse ASA configuration"
        uses: ./.github/actions/parse-json-secret
        with:
          json_secret: ${{ secrets.ASA_CFG }}
          uppercase: 'true'

      - name: "Profile $ASA_PROFILE1 - Setup a2c with asa_ca_handler with profile $ASA_PROFILE1"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.asa_ca_handler
          OPTIONS: |
            api_host: ${{ env.ASA_API_HOST }}
            api_user: ${{ env.ASA_API_USER }}
            api_password: ${{ env.ASA_API_PASSWORD }}
            api_key: ${{ env.ASA_API_KEY }}
            ca_name: ${{ env.ASA_CA_NAME }}
            ca_bundle: ${{ env.ASA_CA_BUNDLE }}
            request_timeout: 30
            request_retries: 3
            profile_name: ${{ env.ASA_PROFILE1 }}
            allowed_domainlist: ["bar.local", "*.acme"]

      - name: "Profile $ASA_PROFILE1 - Setup a2c with asa_ca_handler with profile $ASA_PROFILE1 (post-cfg)"
        run: |
          mkdir -p data/volume/acme_ca
          sudo cp test/ca/certsrv_ca_certs.pem data/volume/acme_ca/ca_certs.pem
          sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\nenrollment_timeout:120/g" data/volume/acme_srv.cfg

      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh install $WEBSRV -m $MODE
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "Create letsencrypt and lego folder"
        run: |
          mkdir certbot
          mkdir lego
          mkdir acme-sh

      - name: "$ASA_PROFILE1 - enrollment"
        uses: ./.github/actions/wf_specific/asa_ca_handler/enroll_profile_1

      - name: "Profile $ASA_PROFILE2 - Setup a2c with asa_ca_handler with profile $ASA_PROFILE1"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.asa_ca_handler
          OPTIONS: |
            api_host: ${{ env.ASA_API_HOST }}
            api_user: ${{ env.ASA_API_USER }}
            api_password: ${{ env.ASA_API_PASSWORD }}
            api_key: ${{ env.ASA_API_KEY }}
            ca_name: ${{ env.ASA_CA_NAME }}
            ca_bundle: ${{ env.ASA_CA_BUNDLE }}
            request_timeout: 30
            request_retries: 3
            profile_name: ${{ env.ASA_PROFILE2 }}
            allowed_domainlist: ["bar.local", "*.acme"]

      - name: "Profile $ASA_PROFILE2 - Setup a2c with asa_ca_handler with profile $ASA_PROFILE1 (post-cfg)"
        run: |
          sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\nenrollment_timeout:120/g" data/volume/acme_srv.cfg

      - name: "Reconfigure a2c"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh restart $WEBSRV
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "$ASA_PROFILE2 - enrollment"
        uses: ./.github/actions/wf_specific/asa_ca_handler/enroll_profile_2

      - name: "Header-info - Setup asa_ca_handler with headerinfo"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.asa_ca_handler
          OPTIONS: |
            api_host: ${{ env.ASA_API_HOST }}
            api_user: ${{ env.ASA_API_USER }}
            api_password: ${{ env.ASA_API_PASSWORD }}
            api_key: ${{ env.ASA_API_KEY }}
            ca_name: ${{ env.ASA_CA_NAME }}
            ca_bundle: ${{ env.ASA_CA_BUNDLE }}
            request_timeout: 30
            request_retries: 3
            profile_name: ${{ env.ASA_PROFILE1 }}
            allowed_domainlist: ["bar.local", "*.acme"]

      - name: "Header-info - Setup asa_ca_handler with headerinfo (post-cfg)"
        run: |
          sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\nenrollment_timeout:120/g" data/volume/acme_srv.cfg
          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nheader_info_list: [\"HTTP_USER_AGENT\"]/g" data/volume/acme_srv.cfg

      - name: "Reconfigure a2c"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh restart $WEBSRV
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "Hederinfo - enrollment"
        uses: ./.github/actions/wf_specific/asa_ca_handler/enroll_headerinfo
        with:
          ASA_PROFILE1: ${{ env.ASA_PROFILE1 }}
          ASA_PROFILE2: ${{ env.ASA_PROFILE2 }}

      - name: "EAB without headerinfo - Setup asa_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.asa_ca_handler
          OPTIONS: |
            api_host: ${{ env.ASA_API_HOST }}
            api_user: ${{ env.ASA_API_USER }}
            api_password: ${{ env.ASA_API_PASSWORD }}
            api_key: ${{ env.ASA_API_KEY }}
            ca_name: ${{ env.ASA_CA_NAME }}
            ca_bundle: ${{ env.ASA_CA_BUNDLE }}
            request_timeout: 30
            request_retries: 3
            profile_name: ${{ env.ASA_PROFILE1 }}
          EXTRA_SECTIONS: |
            [EABhandler]
            eab_handler_module: acme2certifier.eabhandlers.kid_profile_handler
            key_file: /var/www/acme2certifier/volume/acme_ca/kid_profiles.json
            eab_profiling: True

      - name: "Stage kid_profiles"
        uses: ./.github/actions/wf_specific/eab_profiling/stage_kid_profiles
        with:
          SOURCE: .github/actions/wf_specific/eab_profiling/fixtures/asa.json
          DEST: data/volume/acme_ca/kid_profiles.json
          ENVSUBST: "true"
      - name: "EAB without headerinfo - Setup asa_ca_handler (post-cfg)"
        run: |
          sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\nenrollment_timeout:120/g" data/volume/acme_srv.cfg


      - name: "Reconfigure a2c"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh restart $WEBSRV
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "EAB without headerinfo - enrollment"
        uses: ./.github/actions/wf_specific/asa_ca_handler/enroll_eab_wo_headerinfo
        with:
          ASA_CA_NAME1: ${{ env.ASA_CA_NAME1 }}
          ASA_CA_NAME2: ${{ env.ASA_CA_NAME2 }}

      - name: "EAB with headerinfo - Setup asa_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.asa_ca_handler
          OPTIONS: |
            api_host: ${{ env.ASA_API_HOST }}
            api_user: ${{ env.ASA_API_USER }}
            api_password: ${{ env.ASA_API_PASSWORD }}
            api_key: ${{ env.ASA_API_KEY }}
            ca_name: ${{ env.ASA_CA_NAME }}
            ca_bundle: ${{ env.ASA_CA_BUNDLE }}
            request_timeout: 30
            request_retries: 3
            profile_name: ${{ env.ASA_PROFILE1 }}
          EXTRA_SECTIONS: |
            [EABhandler]
            eab_handler_module: acme2certifier.eabhandlers.kid_profile_handler
            key_file: /var/www/acme2certifier/volume/acme_ca/kid_profiles.json
            eab_profiling: True

      - name: "Stage kid_profiles"
        uses: ./.github/actions/wf_specific/eab_profiling/stage_kid_profiles
        with:
          SOURCE: .github/actions/wf_specific/eab_profiling/fixtures/asa.json
          DEST: data/volume/acme_ca/kid_profiles.json
          ENVSUBST: "true"
      - name: "EAB with headerinfo - Setup asa_ca_handler (post-cfg)"
        run: |
          sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\nenrollment_timeout:120/g" data/volume/acme_srv.cfg
          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nheader_info_list: [\"HTTP_USER_AGENT\"]/g" data/volume/acme_srv.cfg


      - name: "Reconfigure a2c"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh restart $WEBSRV
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "EAB with headerinfo - enrollment"
        uses: ./.github/actions/wf_specific/asa_ca_handler/enroll_eab_w_headerinfo
        with:
          ASA_CA_NAME1: ${{ env.ASA_CA_NAME1 }}
          ASA_CA_NAME2: ${{ env.ASA_CA_NAME2 }}

      - name: "ACME Profile - Setup asa_ca_handler with headerinfo"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.asa_ca_handler
          OPTIONS: |
            api_host: ${{ env.ASA_API_HOST }}
            api_user: ${{ env.ASA_API_USER }}
            api_password: ${{ env.ASA_API_PASSWORD }}
            api_key: ${{ env.ASA_API_KEY }}
            ca_name: ${{ env.ASA_CA_NAME }}
            ca_bundle: ${{ env.ASA_CA_BUNDLE }}
            request_timeout: 30
            request_retries: 3
            profile_name: ${{ env.ASA_PROFILE1 }}
            allowed_domainlist: ["bar.local", "*.acme"]

      - name: "ACME Profile - Setup asa_ca_handler with headerinfo (post-cfg)"
        run: |
          sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\nenrollment_timeout:120/g" data/volume/acme_srv.cfg
          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nprofiles={\"$ASA_PROFILE1\": \"http:\/\/foo.bar\/profile1\", \"$ASA_PROFILE2\": \"http:\/\/foo.bar\/profile2\", \"profile3\": \"http:\/\/foo.bar\/profile3\"}/g" data/volume/acme_srv.cfg

      - name: "Reconfigure a2c"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh restart $WEBSRV
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "ACME Profile  - enrollment"
        uses: ./.github/actions/wf_specific/asa_ca_handler/enroll_acmeprofile
        with:
          ASA_PROFILE1: ${{ env.ASA_PROFILE1 }}
          ASA_PROFILE2: ${{ env.ASA_PROFILE2 }}

      - name: "EAB ACME Profiling - Setup asa_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.asa_ca_handler
          OPTIONS: |
            api_host: ${{ env.ASA_API_HOST }}
            api_user: ${{ env.ASA_API_USER }}
            api_password: ${{ env.ASA_API_PASSWORD }}
            api_key: ${{ env.ASA_API_KEY }}
            ca_name: ${{ env.ASA_CA_NAME }}
            ca_bundle: ${{ env.ASA_CA_BUNDLE }}
            request_timeout: 30
            request_retries: 3
            profile_name: ${{ env.ASA_PROFILE1 }}
          EXTRA_SECTIONS: |
            [EABhandler]
            eab_handler_module: acme2certifier.eabhandlers.kid_profile_handler
            key_file: /var/www/acme2certifier/volume/acme_ca/kid_profiles.json
            eab_profiling: True

      - name: "Stage kid_profiles"
        uses: ./.github/actions/wf_specific/eab_profiling/stage_kid_profiles
        with:
          SOURCE: .github/actions/wf_specific/eab_profiling/fixtures/asa.json
          DEST: data/volume/acme_ca/kid_profiles.json
          ENVSUBST: "true"
      - name: "EAB ACME Profiling - Setup asa_ca_handler (post-cfg)"
        run: |
          sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\nenrollment_timeout:120/g" data/volume/acme_srv.cfg
          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nprofiles={\"$ASA_PROFILE1\": \"http:\/\/foo.bar\/profile1\", \"$ASA_PROFILE2\": \"http:\/\/foo.bar\/profile2\", \"profile3\": \"http:\/\/foo.bar\/profile3\"}/g" data/volume/acme_srv.cfg


      - name: "Reconfigure a2c"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh restart $WEBSRV
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "EAB ACME Profiling - enrollment"
        uses: ./.github/actions/wf_specific/asa_ca_handler/enroll_eab_acmeprofile
        with:
          ASA_CA_NAME1: ${{ env.ASA_CA_NAME1 }}
          ASA_CA_NAME2: ${{ env.ASA_CA_NAME2 }}
          ASA_PROFILE1: ${{ env.ASA_PROFILE1 }}

      - name: "Channel teardown"
        if: ${{ always() }}
        uses: ./.github/actions/channel_teardown
        with:
          DEPLOYMENT_TYPE: deb
          ARTIFACT_NAME: test-deb-${{ matrix.websrv }}-${{ matrix.mode }}.tar.gz
          WEBSRV: ${{ matrix.websrv }}
