name: Application Tests - Caddy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
      run_id:
        description: 'Run ID of the producing workflow'
        required: true
        default: '0'
      sha:
        description: 'SHA of the commit to run the workflow on'
        required: true
        default: ''
      called_by_workflow:
        description: 'Name of the producing workflow'
        required: true
        default: 'manual-trigger'
      full_ref:
        description: 'Full git ref of the commit to run the workflow on'
        required: false
        default: ''

jobs:

  # ---------------------------------------------------------
  # Quick guard to validate incoming payload
  # ---------------------------------------------------------
  guard:
    runs-on: ubuntu-latest
    if: ${{ inputs.sha != '' && inputs.run_id != '' && inputs.branch != '' && github.repository == 'grindsa/acme2certifier' }}
    steps:
      - run: |
          echo "Triggered by SHA:    $SHA"
          echo "From branch:         $BRANCH"
          echo "Producer run_id:     $RUN_ID"
        env:
          SHA: ${{ inputs.sha }}
          BRANCH: ${{ inputs.branch }}
          RUN_ID: ${{ inputs.run_id }}

  # ---------------------------------------------------------
  # Test container images (matrix from payload)
  # ---------------------------------------------------------
  test-containers:
    needs: guard
    runs-on: ubuntu-latest
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      matrix:
        ports: ['-p 80:80 -p 443:443', '-p 443:443']
        websrv: ['apache2', 'nginx']
        dbhandler: ['wsgi', 'django']

    steps:
      - name: "checkout GIT"
        uses: actions/checkout@v6

      - name: "Download and import container"
        uses: ./.github/actions/container_load
        with:
          RUN_ID: ${{ inputs.run_id }}
          ARTIFACT_NAME: a2c-${{ inputs.run_id }}.${{ matrix.websrv }}.${{ matrix.dbhandler }}.tar
          DESTINATION_PATH: /tmp
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}

      - name: "Prepare container environment"
        uses: ./.github/actions/container_prep
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}
          CONTAINER_BUILD: false
          NAME_SPACE: acme

      - name: "Setup openssl ca_handler"
        uses: ./.github/actions/setup_openssl_cahandler
        with:
          VOLUME_DIR: "examples/Docker/data"

      - name: "Configure openssl ca_handler"
        run: |
          sudo cp acme2certifier/cahandlers/openssl_ca_handler.py examples/Docker/data/ca_handler.py

      - name: "Bring up a2c container"
        uses: ./.github/actions/container_up
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}

      - name: "Test enrollment"
        uses: ./.github/actions/acme_clients

      - name: "Create caddy folder and copy configuratation files"
        run: |
          mkdir caddy
          cp .github/Caddyfile caddy/
          cp .github/acme2certifier_cabundle.pem caddy

      - name: "Enroll certificate with Caddy"
        run: |
          docker run -d --rm  ${{ matrix.ports }} --network acme -v $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile -v$PWD/caddy/acme2certifier_cabundle.pem:/tmp/acme2certifier_cabundle.pem -v $(pwd)/caddy/config:/config -v $(pwd)/caddy/data:/data --name=caddy caddy:2

      - name: "Sleep for 10s"
        uses: juliangruber/sleep-action@v2.0.4
        with:
          time: 10s

      - name: "Check for logs indicating successful enrollment"
        run: |
          docker logs caddy 2>&1 | grep "successfully downloaded available certificate chains"
          docker logs caddy 2>&1 | grep "certificate obtained successfully"
          docker logs caddy 2>&1 | grep "got renewal info"

      - name: "Check container configuration"
        uses: ./.github/actions/container_check
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}

      - name: "[ * ] Collecting extra failure logs"
        if: ${{ failure() }}
        run: |
          mkdir -p ${{ github.workspace }}/artifact ${{ github.workspace }}/artifact/data
          sudo cp -rp caddy/ ${{ github.workspace }}/artifact/caddy/
          docker logs caddy 2> ${{ github.workspace }}/artifact/caddy.log

      - name: "[ * ] Collecting test logs"
        if: ${{ failure() }}
        uses: ./.github/actions/collect_failure_logs
        with:
          DEPLOYMENT_TYPE: container

      - name: "Sanitize failure artifacts"
        if: ${{ failure() }}
        uses: ./.github/actions/sanitize_artifact_payload
        with:
          ARTIFACT_DIR: ${{ github.workspace }}/artifact
      - name: "[ * ] Uploading artifacts"
        uses: actions/upload-artifact@v7
        if: ${{ failure() }}
        with:
          name: test-containers-${{ github.run_id }}.${{ matrix.websrv }}-${{ matrix.dbhandler }}.tar.gz
          path: ${{ github.workspace }}/artifact/upload/
          retention-days: 1

      - name: "Secure cleanup"
        if: ${{ always() }}
        uses: ./.github/actions/secure_cleanup


