name: Application Tests - Certbot
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
      run_id:
        description: 'Run ID of the producing workflow'
        required: true
        default: '0'
      sha:
        description: 'SHA of the commit to run the workflow on'
        required: true
        default: ''
      called_by_workflow:
        description: 'Name of the producing workflow'
        required: true
        default: 'manual-trigger'
      full_ref:
        description: 'Full git ref of the commit to run the workflow on'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch }}
  cancel-in-progress: true

permissions: {}

jobs:
  guard:
    permissions: {}
    uses: ./.github/workflows/_guard.yml
    with:
      sha: ${{ inputs.sha }}
      run_id: ${{ inputs.run_id }}
      branch: ${{ inputs.branch }}


  # ---------------------------------------------------------
  # Test container images (matrix from payload)
  # ---------------------------------------------------------
  test-containers:
    permissions:
      contents: read
      actions: write
    needs: guard
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      matrix:
        keylength: [2048, 4096]
        websrv: ['apache2', 'nginx']
        dbhandler: ['wsgi', 'django']

    steps:
      - name: "checkout GIT"
        uses: actions/checkout@v7

      - name: "Channel setup"
        uses: ./.github/actions/channel_container_setup
        with:
          RUN_ID: ${{ inputs.run_id }}
          WEB_SRV: ${{ matrix.websrv }}
          DB_HANDLER: ${{ matrix.dbhandler }}
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}
          NAME_SPACE: acme

      - name: "Setup openssl ca_handler"
        uses: ./.github/actions/setup_openssl_cahandler
        with:
          VOLUME_DIR: "examples/Docker/data"

      - name: "Configure openssl ca_handler"
        run: |
          sudo cp acme2certifier/cahandlers/openssl_ca_handler.py examples/Docker/data/ca_handler.py

      - name: "Bring up a2c container"
        uses: ./.github/actions/container_up
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}

      - name: "Wait for ACME directory"
        uses: ./.github/actions/wait_for_directory

      - name: "Create letsencrypt folder"
        run: |
          mkdir certbot

      - name: "Register certbot"
        run: |
          docker run -i --rm --name certbot --network acme -v $PWD/certbot:/etc/letsencrypt/ certbot/certbot register --agree-tos -m 'certbot@example.com' --server http://acme-srv --no-eff-email

      - name: "Enroll HTTP-01 single domain certbot"
        run: |
          docker run -i --rm --name certbot --network acme -v $PWD/certbot:/etc/letsencrypt/ certbot/certbot certonly --rsa-key-size ${{ matrix.keylength }} --server http://acme-srv --standalone --preferred-challenges http -d certbot.acme --cert-name certbot
          sudo openssl verify -CAfile examples/Docker/data/acme_ca/root-ca-cert.pem -untrusted examples/Docker/data/acme_ca/sub-ca-cert.pem certbot/live/certbot/cert.pem

      - name: "Renew HTTP-01 single domain certbot"
        run: |
          docker run -i --rm --name certbot --network acme -v $PWD/certbot:/etc/letsencrypt/ certbot/certbot certonly --rsa-key-size ${{ matrix.keylength }} --server http://acme-srv --standalone --preferred-challenges http -d certbot.acme --cert-name certbot --force-renewal
          sudo openssl verify -CAfile examples/Docker/data/acme_ca/root-ca-cert.pem -untrusted examples/Docker/data/acme_ca/sub-ca-cert.pem certbot/live/certbot/cert.pem

      - name: "Revoke HTTP-01 single domain certbot"
        run: |
          docker run -i --rm --name certbot --network acme -v $PWD/certbot:/etc/letsencrypt/ certbot/certbot revoke --delete-after-revoke --server http://acme-srv  -d certbot.acme --cert-name certbot

      - name: "Enroll HTTP-01 2x domain certbot"
        run: |
          docker run -i --rm --name certbot --network acme --network-alias certbot2 -v $PWD/certbot:/etc/letsencrypt/ certbot/certbot certonly --rsa-key-size ${{ matrix.keylength }} --server http://acme-srv --standalone --preferred-challenges http -d certbot.acme -d certbot2.acme --cert-name certbot
          sudo openssl verify -CAfile examples/Docker/data/acme_ca/root-ca-cert.pem -untrusted examples/Docker/data/acme_ca/sub-ca-cert.pem certbot/live/certbot/cert.pem

      - name: "Renew HTTP-01 2x domain certbot"
        run: |
          docker run -i --rm --name certbot --network acme --network-alias certbot2 -v $PWD/certbot:/etc/letsencrypt/ certbot/certbot certonly --rsa-key-size ${{ matrix.keylength }} --server http://acme-srv --standalone --preferred-challenges http -d certbot.acme -d certbot2.acme --cert-name certbot --force-renewal
          sudo openssl verify -CAfile examples/Docker/data/acme_ca/root-ca-cert.pem -untrusted examples/Docker/data/acme_ca/sub-ca-cert.pem certbot/live/certbot/cert.pem

      - name: "Revoke HTTP-01 2x domain certbot"
        run: |
          docker run -i --rm --name certbot --network acme --network-alias certbot2 -v $PWD/certbot:/etc/letsencrypt/ certbot/certbot revoke --delete-after-revoke --server http://acme-srv  -d certbot.acme -d certbot2.acme --cert-name certbot

      - name: "Check container configuration"
        uses: ./.github/actions/container_check
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}

      - name: "Channel teardown"
        uses: ./.github/actions/channel_teardown
        with:
          DEPLOYMENT_TYPE: container
          ARTIFACT_NAME: test-containers-${{ matrix.keylength }}-${{ matrix.websrv }}-${{ matrix.dbhandler }}.tar.gz
