name: Application Tests - Certbot
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
      run_id:
        description: 'Run ID of the producing workflow'
        required: true
        default: '0'
      sha:
        description: 'SHA of the commit to run the workflow on'
        required: true
        default: ''
      called_by_workflow:
        description: 'Name of the producing workflow'
        required: true
        default: 'manual-trigger'
      full_ref:
        description: 'Full git ref of the commit to run the workflow on'
        required: false
        default: ''

jobs:

  # ---------------------------------------------------------
  # Quick guard to validate incoming payload
  # ---------------------------------------------------------
  guard:
    runs-on: ubuntu-latest
    if: ${{ inputs.sha != '' && inputs.run_id != '' && inputs.branch != '' && github.repository == 'grindsa/acme2certifier' }}
    steps:
      - run: |
          echo "Triggered by SHA:    $SHA"
          echo "From branch:         $BRANCH"
          echo "Producer run_id:     $RUN_ID"
        env:
          SHA: ${{ inputs.sha }}
          BRANCH: ${{ inputs.branch }}
          RUN_ID: ${{ inputs.run_id }}


  # ---------------------------------------------------------
  # Test container images (matrix from payload)
  # ---------------------------------------------------------
  test-containers:
    needs: guard
    runs-on: ubuntu-latest
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      matrix:
        keylength: [2048, 4096]
        websrv: ['apache2', 'nginx']
        dbhandler: ['wsgi', 'django']

    steps:
      - name: "checkout GIT"
        uses: actions/checkout@v6

      - name: "Download and import container"
        uses: ./.github/actions/container_load
        with:
          RUN_ID: ${{ inputs.run_id }}
          ARTIFACT_NAME: a2c-${{ inputs.run_id }}.${{ matrix.websrv }}.${{ matrix.dbhandler }}.tar
          DESTINATION_PATH: /tmp
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}

      - name: "Prepare container environment"
        uses: ./.github/actions/container_prep
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}
          CONTAINER_BUILD: false
          NAME_SPACE: acme

      - name: "Setup openssl ca_handler"
        uses: ./.github/actions/setup_openssl_cahandler
        with:
          VOLUME_DIR: "examples/Docker/data"

      - name: "Configure openssl ca_handler"
        run: |
          sudo cp acme2certifier/cahandlers/openssl_ca_handler.py examples/Docker/data/ca_handler.py

      - name: "Bring up a2c container"
        uses: ./.github/actions/container_up
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}

      - name: "Wait for ACME directory"
        uses: ./.github/actions/wait_for_directory

      - name: "Create letsencrypt folder"
        run: |
          mkdir certbot

      - name: "Register certbot"
        run: |
          docker run -i --rm --name certbot --network acme -v $PWD/certbot:/etc/letsencrypt/ certbot/certbot register --agree-tos -m 'certbot@example.com' --server http://acme-srv --no-eff-email

      - name: "Enroll HTTP-01 single domain certbot"
        run: |
          docker run -i --rm --name certbot --network acme -v $PWD/certbot:/etc/letsencrypt/ certbot/certbot certonly --rsa-key-size ${{ matrix.keylength }} --server http://acme-srv --standalone --preferred-challenges http -d certbot.acme --cert-name certbot
          sudo openssl verify -CAfile examples/Docker/data/acme_ca/root-ca-cert.pem -untrusted examples/Docker/data/acme_ca/sub-ca-cert.pem certbot/live/certbot/cert.pem

      - name: "Renew HTTP-01 single domain certbot"
        run: |
          docker run -i --rm --name certbot --network acme -v $PWD/certbot:/etc/letsencrypt/ certbot/certbot certonly --rsa-key-size ${{ matrix.keylength }} --server http://acme-srv --standalone --preferred-challenges http -d certbot.acme --cert-name certbot --force-renewal
          sudo openssl verify -CAfile examples/Docker/data/acme_ca/root-ca-cert.pem -untrusted examples/Docker/data/acme_ca/sub-ca-cert.pem certbot/live/certbot/cert.pem

      - name: "Revoke HTTP-01 single domain certbot"
        run: |
          docker run -i --rm --name certbot --network acme -v $PWD/certbot:/etc/letsencrypt/ certbot/certbot revoke --delete-after-revoke --server http://acme-srv  -d certbot.acme --cert-name certbot

      - name: "Enroll HTTP-01 2x domain certbot"
        run: |
          docker run -i --rm --name certbot --network acme --network-alias certbot2 -v $PWD/certbot:/etc/letsencrypt/ certbot/certbot certonly --rsa-key-size ${{ matrix.keylength }} --server http://acme-srv --standalone --preferred-challenges http -d certbot.acme -d certbot2.acme --cert-name certbot
          sudo openssl verify -CAfile examples/Docker/data/acme_ca/root-ca-cert.pem -untrusted examples/Docker/data/acme_ca/sub-ca-cert.pem certbot/live/certbot/cert.pem

      - name: "Renew HTTP-01 2x domain certbot"
        run: |
          docker run -i --rm --name certbot --network acme --network-alias certbot2 -v $PWD/certbot:/etc/letsencrypt/ certbot/certbot certonly --rsa-key-size ${{ matrix.keylength }} --server http://acme-srv --standalone --preferred-challenges http -d certbot.acme -d certbot2.acme --cert-name certbot --force-renewal
          sudo openssl verify -CAfile examples/Docker/data/acme_ca/root-ca-cert.pem -untrusted examples/Docker/data/acme_ca/sub-ca-cert.pem certbot/live/certbot/cert.pem

      - name: "Revoke HTTP-01 2x domain certbot"
        run: |
          docker run -i --rm --name certbot --network acme --network-alias certbot2 -v $PWD/certbot:/etc/letsencrypt/ certbot/certbot revoke --delete-after-revoke --server http://acme-srv  -d certbot.acme -d certbot2.acme --cert-name certbot

      - name: "Check container configuration"
        uses: ./.github/actions/container_check
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}

      - name: "[ * ] Collecting test logs"
        if: ${{ failure() }}
        uses: ./.github/actions/collect_failure_logs
        with:
          DEPLOYMENT_TYPE: container

      - name: "Sanitize failure artifacts"
        if: ${{ failure() }}
        uses: ./.github/actions/sanitize_artifact_payload
        with:
          ARTIFACT_DIR: ${{ github.workspace }}/artifact
      - name: "[ * ] Uploading artifacts"
        uses: actions/upload-artifact@v7
        if: ${{ failure() }}
        with:
          name: test-containers-${{ matrix.keylength }}-${{ matrix.websrv }}-${{ matrix.dbhandler }}.tar.gz
          path: ${{ github.workspace }}/artifact/upload/
          retention-days: 1

      - name: "Secure cleanup"
        if: ${{ always() }}
        uses: ./.github/actions/secure_cleanup
