name: CA handler tests - MicrosoftCA

on:
  push:
  pull_request:
    branches: [ devel ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * 6'

jobs:

  mscertsrv_wo_impacket_tests:
    name: "mscertsrv_wo_impacket_tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # max-parallel: 1
      matrix:
        websrv: ['apache2', 'nginx']
        dbhandler: ['wsgi', 'django']
    steps:
    - name: "checkout GIT"
      uses: actions/checkout@v4

    - name: "Modify Dockerfile"
      run: |
        cd examples/Docker/$WEBSRV/$DBHANDLER
        sed -i '/RUN pip3 install impacket --break-system-packages && \\/d' Dockerfile
        sed -i '/rm \/usr\/local\/bin\/\*.py && \\/d' Dockerfile
        sed -i '/rm -rf \/usr\/local\/lib\/python3.12\/dist-packages\/impacket\/examples\/\* && \\/d' Dockerfile
        sed -i "s/    pip3 install -r/RUN pip3 install -r/g" Dockerfile
      env:
        WEBSRV: ${{ matrix.websrv }}
        DBHANDLER: ${{ matrix.dbhandler }}

    - name: "Build container"
      uses: ./.github/actions/container_prep
      with:
        DB_HANDLER: ${{ matrix.dbhandler }}
        WEB_SRV: ${{ matrix.websrv }}
        NAME_SPACE: local

    - name: "Setup tunnel"
      uses: ./.github/actions/wf_specific/ms_ca_handler/tunnel_setup
      with:
        WCCE_SSH_USER: ${{ secrets.WCCE_SSH_USER }}
        WCCE_SSH_HOST: ${{ secrets.WCCE_SSH_HOST }}
        WCCE_SSH_PORT: ${{ secrets.WCCE_SSH_PORT }}
        WCCE_HOST: ${{ secrets.WCCE_HOST }}
        WCCE_FQDN_WOTLD: ${{ secrets.WCCE_FQDN_WOTLD }}
        WCCE_FQDN: ${{ secrets.WCCE_FQDN }}
        WCCE_SSH_KNOWN_HOSTS: ${{ secrets.WCCE_SSH_KNOWN_HOSTS }}
        WCCE_SSH_ACCESS_KEY: ${{ secrets.WCCE_SSH_ACCESS_KEY }}
        NAME_SPACE: local

    - name: "KRB - Setup a2c with mscertsrv_ca_handler"
      run: |
        sudo touch examples/Docker/data/ca_certs.pem
        sudo chmod 777 examples/Docker/data/ca_certs.pem
        sudo cp test/ca/certsrv_ca_certs.pem examples/Docker/data/ca_certs.pem
        sudo touch examples/Docker/data/acme_srv.cfg
        sudo chmod 777 examples/Docker/data/acme_srv.cfg
        sudo head -n -8 .github/openssl_ca_handler.py_acme_srv_default_handler.cfg > examples/Docker/data/acme_srv.cfg
        sudo echo "handler_file: examples/ca_handler/mscertsrv_ca_handler.py" >> examples/Docker/data/acme_srv.cfg
        sudo echo "host: $WCCE_FQDN" >> examples/Docker/data/acme_srv.cfg
        sudo echo "user: $WES_USER" >> examples/Docker/data/acme_srv.cfg
        sudo echo "password: $WES_PASSWORD" >> examples/Docker/data/acme_srv.cfg
        sudo echo "auth_method: gssapi" >> examples/Docker/data/acme_srv.cfg
        sudo echo "template: $WES_TEMPLATE" >> examples/Docker/data/acme_srv.cfg
        sudo echo "ca_bundle: /var/www/acme2certifier/volume/ca_certs.pem" >> examples/Docker/data/acme_srv.cfg
        sudo echo "krb5_config: /var/www/acme2certifier/volume/krb5.conf" >> examples/Docker/data/acme_srv.cfg
        sudo echo "verify: False" >> examples/Docker/data/acme_srv.cfg
        sudo echo "request_timeout: 30" >> examples/Docker/data/acme_srv.cfg
        sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\nenrollment_timeout: 40/g" examples/Docker/data/acme_srv.cfg

        sudo touch examples/Docker/data/krb5.conf
        sudo chmod 777 examples/Docker/data/krb5.conf
        cat <<EOF > examples/Docker/data/krb5.conf
        $WES_KRB5_CONF
        EOF
        cd examples/Docker/
        docker-compose restart
      env:
        WES_HOST: ${{ secrets.WES_HOST }}
        WES_USER: ${{ secrets.WES_USER }}
        WES_PASSWORD: ${{ secrets.WES_PASSWORD }}
        WES_TEMPLATE: ${{ secrets.WES_TEMPLATE }}
        WES_AUTHMETHOD: ${{ secrets.WES_AUTHMETHOD }}
        WCCE_HOST: ${{ secrets.WCCE_HOST }}
        WCCE_ADS_DOMAIN: ${{ secrets.WCCE_ADS_DOMAIN }}
        WES_KRB5_CONF: ${{ secrets.WES_KRB5_CONF }}
        WCCE_FQDN: ${{ secrets.WCCE_FQDN }}
        WCCE_FQDN_WOTLD: ${{ secrets.WCCE_FQDN_WOTLD }}

    - name: "Test enrollment"
      uses: ./.github/actions/acme_clients
      with:
        REVOCATION: "false"
        VERIFY_CERT: "false"
        USE_CERTBOT: "false"
        TEST_ADL: "false"
        NAME_SPACE: local

    - name: "[ * ] collecting test logs"
      if: ${{ failure() }}
      run: |
        mkdir -p ${{ github.workspace }}/artifact/upload
        sudo cp -rp examples/Docker/data/ ${{ github.workspace }}/artifact/data/
        cd examples/Docker
        docker compose logs > ${{ github.workspace }}/artifact/docker-compose.log
        sudo tar -C ${{ github.workspace }}/artifact/ -cvzf ${{ github.workspace }}/artifact/upload/artifact.tar.gz docker-compose.log data

    - name: "[ * ] uploading artificates"
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: mscertsrv_wo_impacket_tests-${{ matrix.websrv }}-${{ matrix.dbhandler }}.tar.gz
        path: ${{ github.workspace }}/artifact/upload/

