name: CA-Handler Tests - EST
# Clientauth tests are not working on testrfc7030 and are done insed openxpi wf
on:
  push:
    branches: [ 'disabled']

#  workflow_dispatch:
#    inputs:
#      branch:
#        description: 'Branch to run the workflow on'
#        required: true
#        default: 'main'
#      run_id:
#        description: 'Run ID of the producing workflow'
#        required: true
#        default: '0'
#      sha:
#        description: 'SHA of the commit to run the workflow on'
#        required: true
#        default: ''
#      called_by_workflow:
#        description: 'Name of the producing workflow'
#        required: true
#        default: 'manual-trigger'
#      full_ref:
#        description: 'Full git ref of the commit to run the workflow on'
#        required: false
#        default: ''

jobs:

  # ---------------------------------------------------------
  # Quick guard to validate incoming payload
  # ---------------------------------------------------------
  guard:
    runs-on: ubuntu-latest
    if: ${{ inputs.sha != '' && inputs.run_id != '' && inputs.branch != '' && github.repository == 'grindsa/acme2certifier' }}
    steps:
      - run: |
          echo "Triggered by SHA:    $SHA"
          echo "From branch:         $BRANCH"
          echo "Producer run_id:     $RUN_ID"
        env:
          SHA: ${{ inputs.sha }}
          BRANCH: ${{ inputs.branch }}
          RUN_ID: ${{ inputs.run_id }}

  # ---------------------------------------------------------
  # Test container images (matrix from payload)
  # ---------------------------------------------------------
  test-containers:
    needs: guard
    runs-on: ubuntu-latest
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        websrv: ['apache2', 'nginx']
        dbhandler: ['wsgi', 'django']

    steps:
      - name: "checkout GIT"
        uses: actions/checkout@v6

      - name: "Download and import container"
        uses: ./.github/actions/container_load
        with:
          RUN_ID: ${{ inputs.run_id }}
          ARTIFACT_NAME: a2c-${{ inputs.run_id }}.${{ matrix.websrv }}.${{ matrix.dbhandler }}.tar
          DESTINATION_PATH: /tmp
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}

      - name: "Prepare container environment"
        uses: ./.github/actions/container_prep
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}
          CONTAINER_BUILD: false
          NAME_SPACE: acme

      - name: "Setup esthandler using http-basic-auth"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "examples/Docker/data"
          HANDLER_MODULE: acme2certifier.cahandlers.est_ca_handler
          OPTIONS: |
            est_host: https://testrfc7030.com:8443
            est_user: estuser
            est_password: estpwd
            ca_bundle: False
            request_timeout: 45
            allowed_domainlist: ["bar.local", "*.acme"]

      - name: "Setup esthandler using http-basic-auth (post-cfg)"
        run: |
          sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\nenrollment_timeout: 40/g" examples/Docker/data/acme_srv.cfg

      - name: "Bring up a2c container"
        uses: ./.github/actions/container_up
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}

      - name: "Test enrollment"
        uses: ./.github/actions/acme_clients
        with:
          REVOCATION: "false"
          VERIFY_CERT: "false"
          USE_CERTBOT: "false"
          TEST_ADL: "true"

      - name: "Verify allowed_domainlist error"
        uses: ./.github/actions/logs_assert
        with:
          DEPLOYMENT_TYPE: container
          PATTERN: "FQDN/SAN [^ ]+ not allowed by configuration"
          REGEX: "true"
          IGNORE_CASE: "true"

      - name: "Check container configuration"
        uses: ./.github/actions/container_check
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}

      - name: "[ * ] Collecting test logs"
        if: ${{ failure() }}
        uses: ./.github/actions/collect_failure_logs
        with:
          DEPLOYMENT_TYPE: container

      - name: "Sanitize failure artifacts"
        if: ${{ failure() }}
        uses: ./.github/actions/sanitize_artifact_payload
        with:
          ARTIFACT_DIR: ${{ github.workspace }}/artifact
      - name: "[ * ] Uploading artifacts"
        uses: actions/upload-artifact@v7
        if: ${{ failure() }}
        with:
          name: test-containers-${{ matrix.websrv }}-${{ matrix.dbhandler }}.tar.gz
          path: ${{ github.workspace }}/artifact/upload/
          retention-days: 1

      - name: "Secure cleanup"
        if: ${{ always() }}
        uses: ./.github/actions/secure_cleanup

  # ---------------------------------------------------------
  # Test RPMs (EL8 & EL9) downloaded from the producer run
  # ---------------------------------------------------------


  test-rpm:
    needs: [guard, test-containers]
    runs-on: ubuntu-latest
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        rhversion: [8, 9]
        mode: ['wsgi', 'django']
    steps:

      - name: "checkout GIT"
        uses: actions/checkout@v6

      - name: "Parse JSON secret"
        uses: ./.github/actions/parse-json-secret
        with:
          json_secret: ${{ secrets.GH_CFG }}

      - name: "Prepare Alma environment"
        uses: ./.github/actions/rpm_prep
        with:
          GH_USER: ${{ env.GH_USER }}
          GH_SBOM_REPO_TOKEN: ${{ env.GH_SBOM_REPO_TOKEN }}
          RH_VERSION: ${{ matrix.rhversion }}
          RPM_BUILD: false

      - name: "Download RPM artifact by name from build run"
        uses: ./.github/actions/download_artifact
        with:
          RUN_ID: ${{ inputs.run_id }}
          ARTIFACT_NAME: acme2certifier-${{ inputs.run_id }}.noarch.rpm
          DESTINATION_PATH: data/
          TOKEN: ${{ secrets.GH_WF_TOKEN }}

      - name: "setup esthandler using http-basic-auth"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.est_ca_handler
          OPTIONS: |
            est_host: https://testrfc7030.com:8443
            est_user: estuser
            est_password: estpwd
            ca_bundle: False
            request_timeout: 30
            allowed_domainlist: ["bar.local", "*.acme"]

      - name: "setup esthandler using http-basic-auth (post-cfg)"
        run: |
          sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\nenrollment_timeout: 40/g" data/volume/acme_srv.cfg

      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-rpm.sh install -m $MODE
        env:
          MODE: ${{ matrix.mode }}

      - name: "Test enrollment"
        uses: ./.github/actions/acme_clients
        with:
          REVOCATION: "false"
          VERIFY_CERT: "false"
          USE_CERTBOT: "false"
          TEST_ADL: "true"

      - name: "Verify allowed_domainlist error"
        uses: ./.github/actions/logs_assert
        with:
          DEPLOYMENT_TYPE: rpm
          PATTERN: "FQDN/SAN [^ ]+ not allowed by configuration"
          REGEX: "true"
          IGNORE_CASE: "true"

      - name: "[ * ] Collecting test logs"
        if: ${{ failure() }}
        uses: ./.github/actions/collect_failure_logs
        with:
          DEPLOYMENT_TYPE: rpm

      - name: "Sanitize failure artifacts"
        if: ${{ failure() }}
        uses: ./.github/actions/sanitize_artifact_payload
        with:
          ARTIFACT_DIR: ${{ github.workspace }}/artifact
      - name: "[ * ] Uploading artifacts"
        uses: actions/upload-artifact@v7
        if: ${{ failure() }}
        with:
          name: test-rpm-rh${{ matrix.rhversion }}-${{ matrix.mode }}.tar.gz
          path: ${{ github.workspace }}/artifact/upload/
          retention-days: 1

      - name: "Secure cleanup"
        if: ${{ always() }}
        uses: ./.github/actions/secure_cleanup

  # ---------------------------------------------------------
  # Test DEB downloaded from the producer run
  # ---------------------------------------------------------


  test-deb:
    needs: [guard, test-rpm]
    runs-on: ubuntu-latest
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        websrv: ['apache2', 'nginx']
        mode: ['wsgi', 'django']

    steps:
      - name: "checkout GIT"
        uses: actions/checkout@v6

      - name: "Prepare Ubuntu environment"
        if: matrix.mode == 'wsgi'
        uses: ./.github/actions/deb_prep
        with:
          DEB_BUILD: false

      - name: "Prepare Ubuntu environment"
        if: matrix.mode == 'django'
        uses: ./.github/actions/deb_prep
        with:
          DEB_BUILD: false
          DJANGO_DB: psql

      - name: "Download DEB artifact by name from build run"
        uses: ./.github/actions/download_artifact
        with:
          RUN_ID: ${{ inputs.run_id }}
          ARTIFACT_NAME: acme2certifier-${{ inputs.run_id }}-1_all.deb
          DESTINATION_PATH: data/
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}

      - name: "setup esthandler using http-basic-auth"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.est_ca_handler
          OPTIONS: |
            est_host: https://testrfc7030.com:8443
            est_user: estuser
            est_password: estpwd
            ca_bundle: False
            request_timeout: 30
            allowed_domainlist: ["bar.local", "*.acme"]

      - name: "setup esthandler using http-basic-auth (post-cfg)"
        run: |
          sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\nenrollment_timeout: 40/g" data/volume/acme_srv.cfg

      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh install $WEBSRV -m $MODE
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "Test enrollment"
        uses: ./.github/actions/acme_clients
        with:
          REVOCATION: "false"
          VERIFY_CERT: "false"
          USE_CERTBOT: "false"

      - name: "[ * ] Collecting test logs"
        if: ${{ failure() }}
        uses: ./.github/actions/collect_failure_logs
        with:
          DEPLOYMENT_TYPE: deb
          WEBSRV: ${{ matrix.websrv }}

      - name: "Sanitize failure artifacts"
        if: ${{ failure() }}
        uses: ./.github/actions/sanitize_artifact_payload
        with:
          ARTIFACT_DIR: ${{ github.workspace }}/artifact
      - name: "[ * ] Uploading artifacts"
        uses: actions/upload-artifact@v7
        if: ${{ failure() }}
        with:
          name: test-deb-${{ matrix.websrv }}-${{ matrix.mode }}.tar.gz
          path: ${{ github.workspace }}/artifact/upload/
          retention-days: 1

      - name: "Secure cleanup"
        if: ${{ always() }}
        uses: ./.github/actions/secure_cleanup


