name: CA-Handler Tests - XCA
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
      run_id:
        description: 'Run ID of the producing workflow'
        required: true
        default: '0'
      sha:
        description: 'SHA of the commit to run the workflow on'
        required: true
        default: ''
      called_by_workflow:
        description: 'Name of the producing workflow'
        required: true
        default: 'manual-trigger'
      full_ref:
        description: 'Full git ref of the commit to run the workflow on'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch }}
  cancel-in-progress: true

permissions: {}

jobs:
  guard:
    permissions: {}
    uses: ./.github/workflows/_guard.yml
    with:
      sha: ${{ inputs.sha }}
      run_id: ${{ inputs.run_id }}
      branch: ${{ inputs.branch }}
  # ---------------------------------------------------------
  # Test container images (matrix from payload)
  # ---------------------------------------------------------
  test-containers:
    permissions:
      contents: read
      actions: write
    needs: guard
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      matrix:
        websrv: ['apache2', 'nginx']
        dbhandler: ['wsgi', 'django']

    steps:
      - name: "checkout GIT"
        uses: actions/checkout@v7

      - name: "Channel setup"
        uses: ./.github/actions/channel_container_setup
        with:
          RUN_ID: ${{ inputs.run_id }}
          WEB_SRV: ${{ matrix.websrv }}
          DB_HANDLER: ${{ matrix.dbhandler }}
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}
          NAME_SPACE: acme

      - name: "Parse XCA configuration from JSON secret"
        uses: ./.github/actions/parse-json-secret
        with:
          json_secret: ${{ secrets.XCA_CFG }}

      - name: "No template - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "examples/Docker/data"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: volume/xca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            allowed_domainlist: ["bar.local", "*.acme"]

      - name: "No template - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          sudo mkdir -p examples/Docker/data/xca
          sudo chmod -R 777 examples/Docker/data/xca
          sudo cp test/ca/acme2certifier-clean.xdb examples/Docker/data/xca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem examples/Docker/data/acme_ca/
          # sudo echo "template_name: $XCA_TEMPLATE" >> examples/Docker/data/acme_srv.cfg

      - name: "Bring up a2c container"
        uses: ./.github/actions/container_up
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}

      - name: "Test enrollment"
        uses: ./.github/actions/acme_clients_enroll
        with:
          TEST_ADL: "true"

      - name: "Verify allowed_domainlist error"
        uses: ./.github/actions/logs_assert
        with:
          DEPLOYMENT_TYPE: container
          PATTERN: "FQDN/SAN [^ ]+ not allowed by configuration"
          REGEX: "true"
          IGNORE_CASE: "true"

      - name: "No Template - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_no_template

      - name: "Template - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "examples/Docker/data"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: volume/xca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}

      - name: "Template - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          sudo mkdir -p examples/Docker/data/xca
          sudo chmod -R 777 examples/Docker/data/xca
          sudo cp test/ca/acme2certifier-clean.xdb examples/Docker/data/xca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem examples/Docker/data/acme_ca/
          cd examples/Docker/
          docker compose restart

      - name: "Template - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_template

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: container

      - name: "Header-info - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "examples/Docker/data"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: volume/xca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}

      - name: "Header-info - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          sudo mkdir -p examples/Docker/data/xca
          sudo chmod -R 777 examples/Docker/data/xca
          sudo cp test/ca/acme2certifier-clean.xdb examples/Docker/data/xca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem examples/Docker/data/acme_ca/
          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nheader_info_list: [\"HTTP_USER_AGENT\"]/g" examples/Docker/data/acme_srv.cfg
          cd examples/Docker/
          docker compose restart

      - name: "Header-info - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_headerinfo

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: container

      - name: "EAB - Setup a2c with xca_ca_handler - profiling"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "examples/Docker/data"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: volume/xca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}
          EXTRA_SECTIONS: |
            [EABhandler]
            eab_handler_module: acme2certifier.eabhandlers.kid_profile_handler
            key_file: volume/kid_profiles.json
            eab_profiling: True

      - name: "Stage kid_profiles"
        uses: ./.github/actions/wf_specific/eab_profiling/stage_kid_profiles
        with:
          SOURCE: .github/actions/wf_specific/eab_profiling/fixtures/xca.json
          DEST: examples/Docker/data/kid_profiles.json
      - name: "EAB - Setup a2c with xca_ca_handler - profiling (post-cfg)"
        run: |
          sudo mkdir -p examples/Docker/data/xca
          sudo chmod -R 777 examples/Docker/data/xca
          sudo cp test/ca/acme2certifier-clean.xdb examples/Docker/data/xca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem examples/Docker/data/acme_ca/
          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nheader_info_list: [\"HTTP_USER_AGENT\"]/g" examples/Docker/data/acme_srv.cfg


          cd examples/Docker/
          docker compose restart

      - name: "EAB - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_eab

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: container

      - name: "EAB subject profiling - Setup a2c with xca_ca_handler "
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "examples/Docker/data"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: volume/xca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}
          EXTRA_SECTIONS: |
            [EABhandler]
            eab_handler_module: acme2certifier.eabhandlers.kid_profile_handler
            key_file: volume/kid_profiles.json
            eab_profiling: True

      - name: "Stage kid_profiles"
        uses: ./.github/actions/wf_specific/eab_profiling/stage_kid_profiles
        with:
          SOURCE: .github/actions/wf_specific/eab_profiling/fixtures/xca_subject.json
          DEST: examples/Docker/data/kid_profiles.json
      - name: "EAB subject profiling - Setup a2c with xca_ca_handler  (post-cfg)"
        run: |
          sudo mkdir -p examples/Docker/data/xca
          sudo chmod -R 777 examples/Docker/data/xca
          sudo cp test/ca/acme2certifier-clean.xdb examples/Docker/data/xca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem examples/Docker/data/acme_ca/

          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nheader_info_list: [\"HTTP_USER_AGENT\"]/g" examples/Docker/data/acme_srv.cfg


          cd examples/Docker/
          docker compose restart

      - name: "EAB subject profiling - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_eab_sp

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: container

      - name: "ACME Profile - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "examples/Docker/data"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: volume/xca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}

      - name: "ACME Profile - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          sudo mkdir -p examples/Docker/data/xca
          sudo chmod -R 777 examples/Docker/data/xca
          sudo cp test/ca/acme2certifier-clean.xdb examples/Docker/data/xca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem examples/Docker/data/acme_ca/
          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nprofiles={\"acme\": \"http:\/\/foo.bar\/profile1\", \"template\": \"http:\/\/foo.bar\/profile2\", \"profile3\": \"http:\/\/foo.bar\/profile3\"}/g" examples/Docker/data/acme_srv.cfg
          cd examples/Docker/
          docker compose restart

      - name: "ACME Profile - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_acmeprofile

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: container

      - name: "EAB ACME Profile - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "examples/Docker/data"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: volume/xca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}
          EXTRA_SECTIONS: |
            [EABhandler]
            eab_handler_module: acme2certifier.eabhandlers.kid_profile_handler
            key_file: volume/kid_profiles.json
            eab_profiling: True

      - name: "Stage kid_profiles"
        uses: ./.github/actions/wf_specific/eab_profiling/stage_kid_profiles
        with:
          SOURCE: .github/actions/wf_specific/eab_profiling/fixtures/xca.json
          DEST: examples/Docker/data/kid_profiles.json
      - name: "EAB ACME Profile - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          sudo mkdir -p examples/Docker/data/xca
          sudo chmod -R 777 examples/Docker/data/xca
          sudo cp test/ca/acme2certifier-clean.xdb examples/Docker/data/xca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem examples/Docker/data/acme_ca/

          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nprofiles={\"acme\": \"http:\/\/foo.bar\/profile1\", \"template\": \"http:\/\/foo.bar\/profile2\", \"profile3\": \"http:\/\/foo.bar\/profile3\"}/g" examples/Docker/data/acme_srv.cfg


          cd examples/Docker/
          docker compose restart

      - name: "EAB ACME Profile - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_eab_acmeprofile

      - name: "Channel teardown"
        if: ${{ always() }}
        uses: ./.github/actions/channel_teardown
        with:
          DEPLOYMENT_TYPE: container
          ARTIFACT_NAME: test-containers-${{ matrix.websrv }}-${{ matrix.dbhandler }}.tar.gz

  # ---------------------------------------------------------
  # Test RPMs (EL8 & EL9) downloaded from the producer run
  # ---------------------------------------------------------


  test-rpm:
    permissions:
      contents: read
      actions: write
    needs: guard
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      matrix:
        rhversion: [8, 9]
        mode: ['wsgi', 'django']

    steps:
      - name: "checkout GIT"
        uses: actions/checkout@v7

      - name: "Channel setup"
        uses: ./.github/actions/channel_rpm_setup
        with:
          RUN_ID: ${{ inputs.run_id }}
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}
          RH_VERSION: ${{ matrix.rhversion }}
          JSON_SECRET: ${{ secrets.GH_CFG }}

      - name: "Parse XCA configuration from JSON secret"
        uses: ./.github/actions/parse-json-secret
        with:
          json_secret: ${{ secrets.XCA_CFG }}

      - name: "No template - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: volume/acme_ca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            allowed_domainlist: ["bar.local", "*.acme"]

      - name: "No template - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          mkdir -p data/volume/acme_ca
          sudo cp test/ca/acme2certifier-clean.xdb data/volume/acme_ca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/volume/acme_ca/
          # sudo echo "template_name: $XCA_TEMPLATE" >> data/volume/acme_srv.cfg

      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-rpm.sh install -m $MODE
        env:
          MODE: ${{ matrix.mode }}

      - name: "Test enrollment"
        uses: ./.github/actions/acme_clients_enroll
        with:
          TEST_ADL: "true"

      - name: "Verify allowed_domainlist error"
        uses: ./.github/actions/logs_assert
        with:
          DEPLOYMENT_TYPE: rpm
          PATTERN: "FQDN/SAN [^ ]+ not allowed by configuration"
          REGEX: "true"
          IGNORE_CASE: "true"

      - name: "No Template - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_no_template

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: rpm

      - name: "Template - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: volume/acme_ca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}

      - name: "Template - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          mkdir -p data/volume/acme_ca
          sudo cp test/ca/acme2certifier-clean.xdb data/volume/acme_ca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/volume/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/volume/acme_ca/

      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-rpm.sh restart
        env:
          MODE: ${{ matrix.mode }}

      - name: "Template - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_template

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: rpm

      - name: "Header-info - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: volume/acme_ca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}

      - name: "Header-info - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          mkdir -p data/volume/acme_ca
          sudo cp test/ca/acme2certifier-clean.xdb data/volume/acme_ca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/volume/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/volume/acme_ca/
          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nheader_info_list: [\"HTTP_USER_AGENT\"]/g" data/volume/acme_srv.cfg

      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-rpm.sh restart
        env:
          MODE: ${{ matrix.mode }}

      - name: "Header-info - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_headerinfo

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: rpm

      - name: "EAB - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: volume/acme_ca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}
          EXTRA_SECTIONS: |
            [EABhandler]
            eab_handler_module: acme2certifier.eabhandlers.kid_profile_handler
            key_file: /opt/acme2certifier/volume/acme_ca/kid_profiles.json
            eab_profiling: True

      - name: "Stage kid_profiles"
        uses: ./.github/actions/wf_specific/eab_profiling/stage_kid_profiles
        with:
          SOURCE: .github/actions/wf_specific/eab_profiling/fixtures/xca.json
          DEST: data/volume/acme_ca/kid_profiles.json
      - name: "EAB - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          mkdir -p data/volume/acme_ca
          sudo cp test/ca/acme2certifier-clean.xdb data/volume/acme_ca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/volume/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/volume/acme_ca/

          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nheader_info_list: [\"HTTP_USER_AGENT\"]/g" data/volume/acme_srv.cfg


      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-rpm.sh restart
        env:
          MODE: ${{ matrix.mode }}

      - name: "EAB - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_eab

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: rpm

      - name: "EAB subject profiling - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: volume/acme_ca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}
          EXTRA_SECTIONS: |
            [EABhandler]
            eab_handler_module: acme2certifier.eabhandlers.kid_profile_handler
            key_file: /opt/acme2certifier/volume/acme_ca/kid_profiles.json
            eab_profiling: True

      - name: "Stage kid_profiles"
        uses: ./.github/actions/wf_specific/eab_profiling/stage_kid_profiles
        with:
          SOURCE: .github/actions/wf_specific/eab_profiling/fixtures/xca_subject.json
          DEST: data/volume/acme_ca/kid_profiles.json
      - name: "EAB subject profiling - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          mkdir -p data/volume/acme_ca
          sudo cp test/ca/acme2certifier-clean.xdb data/volume/acme_ca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/volume/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/volume/acme_ca/

          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nheader_info_list: [\"HTTP_USER_AGENT\"]/g" data/volume/acme_srv.cfg


      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-rpm.sh install -m $MODE
          docker exec acme-srv bash /tmp/acme2certifier/a2c-rpm.sh restart
        env:
          MODE: ${{ matrix.mode }}

      - name: "EAB subject profiling - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_eab_sp
        with:
          DEPLOYMENT_TYPE: "rpm"

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: rpm

      - name: "ACME Profile - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: volume/acme_ca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}

      - name: "ACME Profile - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          mkdir -p data/volume/acme_ca
          sudo cp test/ca/acme2certifier-clean.xdb data/volume/acme_ca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/volume/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/volume/acme_ca/
          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nprofiles={\"acme\": \"http:\/\/foo.bar\/profile1\", \"template\": \"http:\/\/foo.bar\/profile2\", \"profile3\": \"http:\/\/foo.bar\/profile3\"}/g" data/volume/acme_srv.cfg

      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-rpm.sh restart
        env:
          MODE: ${{ matrix.mode }}

      - name: "ACME Profile - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_acmeprofile

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: rpm

      - name: "EAB ACME Profile - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: volume/acme_ca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}
          EXTRA_SECTIONS: |
            [EABhandler]
            eab_handler_module: acme2certifier.eabhandlers.kid_profile_handler
            key_file: /opt/acme2certifier/volume/acme_ca/kid_profiles.json
            eab_profiling: True

      - name: "Stage kid_profiles"
        uses: ./.github/actions/wf_specific/eab_profiling/stage_kid_profiles
        with:
          SOURCE: .github/actions/wf_specific/eab_profiling/fixtures/xca.json
          DEST: data/volume/acme_ca/kid_profiles.json
      - name: "EAB ACME Profile - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          mkdir -p data/volume/acme_ca
          sudo cp test/ca/acme2certifier-clean.xdb data/volume/acme_ca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/volume/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/volume/acme_ca/

          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nprofiles={\"acme\": \"http:\/\/foo.bar\/profile1\", \"template\": \"http:\/\/foo.bar\/profile2\", \"profile3\": \"http:\/\/foo.bar\/profile3\"}/g" data/volume/acme_srv.cfg


      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-rpm.sh restart
        env:
          MODE: ${{ matrix.mode }}

      - name: "EAB ACME Profile - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_eab_acmeprofile

      - name: "Channel teardown"
        if: ${{ always() }}
        uses: ./.github/actions/channel_teardown
        with:
          DEPLOYMENT_TYPE: rpm
          ARTIFACT_NAME: test-rpm-rh${{ matrix.rhversion }}.tar.gz

  # ---------------------------------------------------------
  # Test DEB downloaded from the producer run
  # ---------------------------------------------------------


  test-deb:
    permissions:
      contents: read
      actions: write
    needs: guard
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      matrix:
        websrv: ['apache2', 'nginx']
        mode: ['wsgi', 'django']

    steps:
      - name: "checkout GIT"
        uses: actions/checkout@v7

      - name: "Channel setup"
        uses: ./.github/actions/channel_deb_setup
        with:
          RUN_ID: ${{ inputs.run_id }}
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}
          DJANGO_DB: ${{ matrix.mode == 'django' && 'psql' || '' }}

      - name: "Parse XCA configuration from JSON secret"
        uses: ./.github/actions/parse-json-secret
        with:
          json_secret: ${{ secrets.XCA_CFG }}

      - name: "No template - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: /var/www/acme2certifier/volume/acme_ca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            allowed_domainlist: ["bar.local", "*.acme"]

      - name: "No template - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          mkdir -p data/volume/acme_ca
          sudo cp test/ca/acme2certifier-clean.xdb data/volume/acme_ca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/volume/acme_ca/
          # sudo echo "template_name: $XCA_TEMPLATE" >> data/volume/acme_srv.cfg

      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh install $WEBSRV -m $MODE
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "Test enrollment"
        uses: ./.github/actions/acme_clients_enroll
        with:
          TEST_ADL: "true"

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: deb

      - name: "No Template - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_no_template

      - name: "Template - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: /var/www/acme2certifier/volume/acme_ca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}

      - name: "Template - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          mkdir -p data/volume/acme_ca
          sudo cp test/ca/acme2certifier-clean.xdb data/volume/acme_ca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/volume/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/volume/acme_ca/

      - name: "Reconfigure a2c "
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh restart $WEBSRV
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "Template - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_template

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: deb

      - name: "Header-info - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: /var/www/acme2certifier/volume/acme_ca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}

      - name: "Header-info - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          mkdir -p data/volume/acme_ca
          sudo cp test/ca/acme2certifier-clean.xdb data/volume/acme_ca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/volume/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/volume/acme_ca/
          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nheader_info_list: [\"HTTP_USER_AGENT\"]/g" data/volume/acme_srv.cfg

      - name: "Reconfigure a2c "
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh restart $WEBSRV
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "Header-info - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_headerinfo

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: deb

      - name: "EAB - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: /var/www/acme2certifier/volume/acme_ca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}
          EXTRA_SECTIONS: |
            [EABhandler]
            eab_handler_module: acme2certifier.eabhandlers.kid_profile_handler
            key_file: /var/www/acme2certifier/volume/acme_ca/kid_profiles.json
            eab_profiling: True

      - name: "Stage kid_profiles"
        uses: ./.github/actions/wf_specific/eab_profiling/stage_kid_profiles
        with:
          SOURCE: .github/actions/wf_specific/eab_profiling/fixtures/xca.json
          DEST: data/volume/acme_ca/kid_profiles.json
      - name: "EAB - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          mkdir -p data/volume/acme_ca
          sudo cp test/ca/acme2certifier-clean.xdb data/volume/acme_ca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/volume/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/volume/acme_ca/

          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nheader_info_list: [\"HTTP_USER_AGENT\"]/g" data/volume/acme_srv.cfg


      - name: "Reconfigure a2c "
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh restart $WEBSRV
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "EAB - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_eab

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: deb

      - name: "EAB subject profiling - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: /var/www/acme2certifier/volume/acme_ca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}
          EXTRA_SECTIONS: |
            [EABhandler]
            eab_handler_module: acme2certifier.eabhandlers.kid_profile_handler
            key_file: /var/www/acme2certifier/volume/acme_ca/kid_profiles.json
            eab_profiling: True

      - name: "Stage kid_profiles"
        uses: ./.github/actions/wf_specific/eab_profiling/stage_kid_profiles
        with:
          SOURCE: .github/actions/wf_specific/eab_profiling/fixtures/xca_subject.json
          DEST: data/volume/acme_ca/kid_profiles.json
      - name: "EAB subject profiling - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          mkdir -p data/volume/acme_ca
          sudo cp test/ca/acme2certifier-clean.xdb data/volume/acme_ca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/volume/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/volume/acme_ca/

          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nheader_info_list: [\"HTTP_USER_AGENT\"]/g" data/volume/acme_srv.cfg


      - name: "Reconfigure a2c "
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh restart $WEBSRV
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "EAB subject profiling - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_eab_sp
        with:
          DEPLOYMENT_TYPE: "deb"

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: deb

      - name: "ACME Profile - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: /var/www/acme2certifier/volume/acme_ca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}

      - name: "ACME Profile - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          mkdir -p data/volume/acme_ca
          sudo cp test/ca/acme2certifier-clean.xdb data/volume/acme_ca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/volume/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/volume/acme_ca/
          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nprofiles={\"acme\": \"http:\/\/foo.bar\/profile1\", \"template\": \"http:\/\/foo.bar\/profile2\", \"profile3\": \"http:\/\/foo.bar\/profile3\"}/g" data/volume/acme_srv.cfg

      - name: "Reconfigure a2c "
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh restart $WEBSRV
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "ACME Profile - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_acmeprofile

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: deb

      - name: "EAB ACME Profile - Setup a2c with xca_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.xca_ca_handler
          OPTIONS: |
            xdb_file: /var/www/acme2certifier/volume/acme_ca/${{ env.XCA_DB_NAME }}
            issuing_ca_name: ${{ env.XCA_ISSUING_CA }}
            passphrase: ${{ env.XCA_PASSPHRASE }}
            ca_cert_chain_list: ["root-ca"]
            template_name: ${{ env.XCA_TEMPLATE }}
          EXTRA_SECTIONS: |
            [EABhandler]
            eab_handler_module: acme2certifier.eabhandlers.kid_profile_handler
            key_file: /var/www/acme2certifier/volume/acme_ca/kid_profiles.json
            eab_profiling: True

      - name: "Stage kid_profiles"
        uses: ./.github/actions/wf_specific/eab_profiling/stage_kid_profiles
        with:
          SOURCE: .github/actions/wf_specific/eab_profiling/fixtures/xca.json
          DEST: data/volume/acme_ca/kid_profiles.json
      - name: "EAB ACME Profile - Setup a2c with xca_ca_handler (post-cfg)"
        run: |
          mkdir -p data/volume/acme_ca
          sudo cp test/ca/acme2certifier-clean.xdb data/volume/acme_ca/$XCA_DB_NAME
          sudo mkdir -p examples/Docker/data/volume/acme_ca/certs
          sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/volume/acme_ca/

          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nprofiles={\"acme\": \"http:\/\/foo.bar\/profile1\", \"template\": \"http:\/\/foo.bar\/profile2\", \"profile3\": \"http:\/\/foo.bar\/profile3\"}/g" data/volume/acme_srv.cfg


      - name: "Reconfigure a2c "
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh restart $WEBSRV
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "EAB ACME Profile - enrollment"
        uses: ./.github/actions/wf_specific/xca_ca_handler/enroll_eab_acmeprofile

      - name: "Channel teardown"
        if: ${{ always() }}
        uses: ./.github/actions/channel_teardown
        with:
          DEPLOYMENT_TYPE: deb
          ARTIFACT_NAME: test-deb-${{ matrix.websrv }}-${{ matrix.mode }}.tar.gz
          WEBSRV: ${{ matrix.websrv }}
