name: CA handler tests - DogTag
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
      run_id:
        description: 'Run ID of the producing workflow'
        required: true
        default: '0'
      sha:
        description: 'SHA of the commit to run the workflow on'
        required: true
        default: ''
      called_by_workflow:
        description: 'Name of the producing workflow'
        required: true
        default: 'manual-trigger'
      full_ref:
        description: 'Full git ref of the commit to run the workflow on'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch }}
  cancel-in-progress: true

permissions: {}

jobs:
  guard:
    permissions: {}
    uses: ./.github/workflows/_guard.yml
    with:
      sha: ${{ inputs.sha }}
      run_id: ${{ inputs.run_id }}
      branch: ${{ inputs.branch }}

  # ---------------------------------------------------------
  # Test container images (matrix from payload)
  # ---------------------------------------------------------
  acme-test-containers:
    permissions:
      contents: read
      actions: write
    needs: guard
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      matrix:
        websrv: ['apache2', 'nginx']
        dbhandler: ['wsgi', 'django']

    steps:
      - name: "checkout GIT"
        uses: actions/checkout@v6

      - name: "Channel setup"
        uses: ./.github/actions/channel_container_setup
        with:
          RUN_ID: ${{ inputs.run_id }}
          WEB_SRV: ${{ matrix.websrv }}
          DB_HANDLER: ${{ matrix.dbhandler }}
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}
          NAME_SPACE: acme

      - name: Parse DOGTAG config
        uses: ./.github/actions/parse-json-secret
        with:
          json_secret: ${{ secrets.DOGTAG_CFG }}

      - name: "Prepare dogtag server"
        uses: ./.github/actions/wf_specific/dogtag_ca_handler/dogtag_prep
        with:
          RUNNER_IP: ${{ env.RUNNER_IP }}
          NAME_SPACE: acme
          ADMIN_USER: ${{ secrets.DOGTAG_ADMIN_USER }}
          ADMIN_PASSWORD: ${{ secrets.DOGTAG_ADMIN_PASSWORD }}
          A2C_USER: ${{ secrets.DOGTAG_A2C_USER }}
          A2C_PASSWORD: ${{ secrets.DOGTAG_A2C_PASSWORD }}

      - name: "Setup dogtag_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "examples/Docker/data"
          HANDLER_MODULE: acme2certifier.cahandlers.dogtag_ca_handler
          OPTIONS: |
            api_host: https://dogtag.acme:8443
            client_key: volume/acme/${{ env.A2C_USER }}.key
            client_cert: volume/acme/${{ env.A2C_USER }}.crt
            ca_bundle: False
            profile: WebserverSanOnly
            certrequest_approve: True
            enrollment_config_log: True
            allowed_domainlist: ["*.foo.bar", "*.acme"]
        env:
          ADMIN_USER: ${{ inputs.ADMIN_USER }}

      - name: "Setup dogtag_ca_handler (post-cfg)"
        run: |
          sudo mkdir -p examples/Docker/data/acme
          sudo cp dogtag/$A2C_USER* examples/Docker/data/acme/
          sudo chmod -R 777 examples/Docker/data/acme
          # sudo sed -i "s/challenge_validation_disable: False/challenge_validation_disable: True/g" examples/Docker/data/acme_srv.cfg
          # sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\ncert_reusage_timeframe: 1800\nenrollment_timeout: 15\ncert_operations_log: True/g" examples/Docker/data/acme_srv.cfg
        env:
          ADMIN_USER: ${{ inputs.ADMIN_USER }}

      - name: "Bring up a2c container"
        uses: ./.github/actions/container_up
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}

      - name: "Generate UUID"
        run: |
          echo UUID=$(uuidgen | cut -d "-" -f1) >> $GITHUB_ENV
      - run: echo "UUID ${{ env.UUID }}"

      - name: "Test enrollment"
        uses: ./.github/actions/acme_clients
        with:
          TEST_ADL: "true"
          USE_RSA: "true"
          USE_CERTBOT: "false"
          HOSTNAME_SUFFIX: -${{ env.UUID }}

      - name: "Check container configuration"
        uses: ./.github/actions/container_check
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: container

      - name: "ACME Profiling - Setup a2c with dogtag_ca_handler"
        run: |
          # disable challenge validation to avoid issues with profile tests
          sudo sed -i "s/challenge_validation_disable: False/challenge_validation_disable: True/g" examples/Docker/data/acme_srv.cfg
          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nprofiles={\"WebserverSanOnly\": \"http:\/\/foo.bar\/WebserverSanOnly\", \"WebserverSanOnlyTLSClient\": \"http:\/\/foo.bar\/WebserverSanOnlyTLSClient\", \"WebserverSanOnlyTLSServer\": \"http:\/\/foo.bar\/WebserverSanOnlyTLSServer\"}/g" examples/Docker/data/acme_srv.cfg
          cd examples/Docker/
          docker compose restart

      - name: "ACME Profiling - Test enrollment"
        uses: ./.github/actions/wf_specific/dogtag_ca_handler/enroll_acmeprofile

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: container

      - name: "Stage kid_profiles"
        uses: ./.github/actions/wf_specific/eab_profiling/stage_kid_profiles
        with:
          SOURCE: .github/actions/wf_specific/eab_profiling/fixtures/dogtag.json
          DEST: examples/Docker/data/kid_profiles.json
      - name: "EAB Profiling - Setup a2c with dogtag_ca_handler"
        run: |
          sudo echo -e "\n[EABhandler]" >> examples/Docker/data/acme_srv.cfg
          sudo echo "eab_handler_module: acme2certifier.eabhandlers.kid_profile_handler" >> examples/Docker/data/acme_srv.cfg
          sudo echo "key_file: volume/kid_profiles.json" >> examples/Docker/data/acme_srv.cfg
          sudo echo "eab_profiling: True" >> examples/Docker/data/acme_srv.cfg


          cd examples/Docker/
          docker compose restart

      - name: "EAB Profiling - Test enrollment"
        uses: ./.github/actions/wf_specific/dogtag_ca_handler/enroll_eabprofile

      - name: "Channel teardown"
        uses: ./.github/actions/channel_teardown
        with:
          DEPLOYMENT_TYPE: container
          ARTIFACT_NAME: acme-test-containers-${{ matrix.websrv }}-${{ matrix.dbhandler }}.tar.gz

  test-rpm:
    permissions:
      contents: read
      actions: write
    needs: guard
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      matrix:
        rhversion: [8, 9]
        mode: ['wsgi', 'django']
    steps:
      - name: "checkout GIT"
        uses: actions/checkout@v6


      - name: "Channel setup"
        uses: ./.github/actions/channel_rpm_setup
        with:
          RUN_ID: ${{ inputs.run_id }}
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}
          RH_VERSION: ${{ matrix.rhversion }}
          JSON_SECRET: ${{ secrets.GH_CFG }}

      - name: Parse DOGTAG config
        uses: ./.github/actions/parse-json-secret
        with:
          json_secret: ${{ secrets.DOGTAG_CFG }}

      - name: "Prepare dogtag server"
        uses: ./.github/actions/wf_specific/dogtag_ca_handler/dogtag_prep
        with:
          RUNNER_IP: ${{ env.RUNNER_IP }}
          NAME_SPACE: acme
          ADMIN_USER: ${{ secrets.DOGTAG_ADMIN_USER }}
          ADMIN_PASSWORD: ${{ secrets.DOGTAG_ADMIN_PASSWORD }}
          A2C_USER: ${{ secrets.DOGTAG_A2C_USER }}
          A2C_PASSWORD: ${{ secrets.DOGTAG_A2C_PASSWORD }}

      - name: "Setup dogtag_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.dogtag_ca_handler
          OPTIONS: |
            api_host: https://dogtag.acme:8443
            client_key: /opt/acme2certifier/volume/${{ env.A2C_USER }}.key
            client_cert: /opt/acme2certifier/volume/${{ env.A2C_USER }}.crt
            ca_bundle: False
            profile: WebserverSanOnly
            certrequest_approve: True
            enrollment_config_log: True
            allowed_domainlist: ["*.foo.bar", "*.acme"]
        env:
          ADMIN_USER: ${{ inputs.ADMIN_USER }}

      - name: "Setup dogtag_ca_handler (post-cfg)"
        run: |
          sudo mkdir -p data/volume/acme_ca/
          sudo cp dogtag/$A2C_USER* data/volume/
          sudo chmod -R 777 data/volume/
          # sudo sed -i "s/challenge_validation_disable: False/challenge_validation_disable: True/g" data/volume/acme_srv.cfg
          # sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\ncert_reusage_timeframe: 1800\nenrollment_timeout: 15\ncert_operations_log: True/g" data/volume/acme_srv.cfg
        env:
          ADMIN_USER: ${{ inputs.ADMIN_USER }}

      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-rpm.sh install -m $MODE
        env:
          MODE: ${{ matrix.mode }}

      - name: "Generate UUID"
        run: |
          echo UUID=$(uuidgen | cut -d "-" -f1) >> $GITHUB_ENV
      - run: echo "UUID ${{ env.UUID }}"

      - name: "Test enrollment"
        uses: ./.github/actions/acme_clients
        with:
          TEST_ADL: "true"
          USE_RSA: "true"
          USE_CERTBOT: "false"
          HOSTNAME_SUFFIX: -${{ env.UUID }}

      - name: "Verify allowed_domainlist error"
        uses: ./.github/actions/logs_assert
        with:
          DEPLOYMENT_TYPE: rpm
          PATTERN: "FQDN/SAN [^ ]+ not allowed by configuration"
          REGEX: "true"
          IGNORE_CASE: "true"

      - name: "ACME Profiling - Setup a2c with dogtag_ca_handler"
        run: |
          # disable challenge validation to avoid issues with profile tests
          sudo sed -i "s/challenge_validation_disable: False/challenge_validation_disable: True/g" data/volume/acme_srv.cfg
          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nprofiles={\"WebserverSanOnly\": \"http:\/\/foo.bar\/WebserverSanOnly\", \"WebserverSanOnlyTLSClient\": \"http:\/\/foo.bar\/WebserverSanOnlyTLSClient\", \"WebserverSanOnlyTLSServer\": \"http:\/\/foo.bar\/WebserverSanOnlyTLSServer\"}/g" data/volume/acme_srv.cfg

      - name: "Reconfigure a2c"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-rpm.sh restart
        env:
          MODE: ${{ matrix.mode }}

      - name: "ACME Profiling - Test enrollment"
        uses: ./.github/actions/wf_specific/dogtag_ca_handler/enroll_acmeprofile

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: rpm

      - name: "Stage kid_profiles"
        uses: ./.github/actions/wf_specific/eab_profiling/stage_kid_profiles
        with:
          SOURCE: .github/actions/wf_specific/eab_profiling/fixtures/dogtag.json
          DEST: data/volume/acme_ca/kid_profiles.json
      - name: "EAB Profiling - Setup a2c with dogtag_ca_handler"
        run: |
          sudo echo -e "\n[EABhandler]" >> data/volume/acme_srv.cfg
          sudo echo "eab_handler_module: acme2certifier.eabhandlers.kid_profile_handler" >> data/volume/acme_srv.cfg
          sudo echo "key_file: /opt/acme2certifier/volume/acme_ca/kid_profiles.json" >> data/volume/acme_srv.cfg
          sudo echo "eab_profiling: True" >> data/volume/acme_srv.cfg


      - name: "Reconfigure a2c"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-rpm.sh restart
        env:
          MODE: ${{ matrix.mode }}

      - name: "EAB Profiling - Test enrollment"
        uses: ./.github/actions/wf_specific/dogtag_ca_handler/enroll_eabprofile

      - name: "Channel teardown"
        uses: ./.github/actions/channel_teardown
        with:
          DEPLOYMENT_TYPE: rpm
          ARTIFACT_NAME: test-rpm-rh${{ matrix.rhversion }}-${{ matrix.mode }}.tar.gz

  # ---------------------------------------------------------
  # Test DEB downloaded from the producer run
  # ---------------------------------------------------------


  test-deb:
    permissions:
      contents: read
      actions: write
    needs: guard
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      matrix:
        websrv: ['apache2', 'nginx']
        mode: ['wsgi', 'django']

    steps:
      - name: "checkout GIT"
        uses: actions/checkout@v6

      - name: "Channel setup"
        uses: ./.github/actions/channel_deb_setup
        with:
          RUN_ID: ${{ inputs.run_id }}
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}
          DJANGO_DB: ${{ matrix.mode == 'django' && 'psql' || '' }}
          PARSE_GH_CFG: "true"
          JSON_SECRET: ${{ secrets.GH_CFG }}
          NAME_SPACE: "acme"

      - name: Parse DOGTAG config
        uses: ./.github/actions/parse-json-secret
        with:
          json_secret: ${{ secrets.DOGTAG_CFG }}

      - name: "Prepare dogtag server"
        uses: ./.github/actions/wf_specific/dogtag_ca_handler/dogtag_prep
        with:
          RUNNER_IP: ${{ env.RUNNER_IP }}
          NAME_SPACE: acme
          ADMIN_USER: ${{ secrets.DOGTAG_ADMIN_USER }}
          ADMIN_PASSWORD: ${{ secrets.DOGTAG_ADMIN_PASSWORD }}
          A2C_USER: ${{ secrets.DOGTAG_A2C_USER }}
          A2C_PASSWORD: ${{ secrets.DOGTAG_A2C_PASSWORD }}

      - name: "Generate UUID"
        run: |
          echo UUID=$(uuidgen | cut -d "-" -f1) >> $GITHUB_ENV
      - run: echo "UUID ${{ env.UUID }}"

      - name: "Setup dogtag_ca_handler"
        uses: ./.github/actions/setup_cahandler_cfg
        with:
          VOLUME_DIR: "data/volume"
          HANDLER_MODULE: acme2certifier.cahandlers.dogtag_ca_handler
          OPTIONS: |
            api_host: https://dogtag.acme:8443
            client_key: /var/www/acme2certifier/volume/${{ env.A2C_USER }}.key
            client_cert: /var/www/acme2certifier/volume/${{ env.A2C_USER }}.crt
            ca_bundle: False
            profile: WebserverSanOnly
            certrequest_approve: True
            enrollment_config_log: True
            allowed_domainlist: ["*.foo.bar", "*.acme"]
        env:
          ADMIN_USER: ${{ inputs.ADMIN_USER }}

      - name: "Setup dogtag_ca_handler (post-cfg)"
        run: |
          sudo mkdir -p data/volume/acme_ca/
          sudo cp dogtag/$A2C_USER* data/volume/
          sudo chmod -R 777 data/volume/
          # sudo sed -i "s/challenge_validation_disable: False/challenge_validation_disable: True/g" data/volume/acme_srv.cfg
          # sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\ncert_reusage_timeframe: 1800\nenrollment_timeout: 15\ncert_operations_log: True/g" data/volume/acme_srv.cfg
        env:
          ADMIN_USER: ${{ inputs.ADMIN_USER }}

      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh install $WEBSRV -m $MODE
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "Generate UUID"
        run: |
          echo UUID=$(uuidgen | cut -d "-" -f1) >> $GITHUB_ENV
      - run: echo "UUID ${{ env.UUID }}"

      - name: "Test enrollment"
        uses: ./.github/actions/acme_clients
        with:
          TEST_ADL: "true"
          USE_RSA: "true"
          USE_CERTBOT: "false"
          HOSTNAME_SUFFIX: -${{ env.UUID }}

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: deb

      - name: "ACME Profiling - Setup a2c with dogtag_ca_handler"
        run: |
          # disable challenge validation to avoid issues with profile tests
          sudo sed -i "s/challenge_validation_disable: False/challenge_validation_disable: True/g" data/volume/acme_srv.cfg
          sudo sed -i "s/tnauthlist_support: False/tnauthlist_support: False\nprofiles={\"WebserverSanOnly\": \"http:\/\/foo.bar\/WebserverSanOnly\", \"WebserverSanOnlyTLSClient\": \"http:\/\/foo.bar\/WebserverSanOnlyTLSClient\", \"WebserverSanOnlyTLSServer\": \"http:\/\/foo.bar\/WebserverSanOnlyTLSServer\"}/g" data/volume/acme_srv.cfg

      - name: "Reconfigure a2c "
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh restart $WEBSRV
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "ACME Profiling - Test enrollment"
        uses: ./.github/actions/wf_specific/dogtag_ca_handler/enroll_acmeprofile

      - name: "Flush logs"
        uses: ./.github/actions/logs_flush
        with:
          DEPLOYMENT_TYPE: deb

      - name: "Stage kid_profiles"
        uses: ./.github/actions/wf_specific/eab_profiling/stage_kid_profiles
        with:
          SOURCE: .github/actions/wf_specific/eab_profiling/fixtures/dogtag.json
          DEST: data/volume/acme_ca/kid_profiles.json
      - name: "EAB Profiling - Setup a2c with dogtag_ca_handler"
        run: |
          sudo echo -e "\n[EABhandler]" >> data/volume/acme_srv.cfg
          sudo echo "eab_handler_module: acme2certifier.eabhandlers.kid_profile_handler" >> data/volume/acme_srv.cfg
          sudo echo "key_file: /var/www/acme2certifier/volume/acme_ca/kid_profiles.json" >> data/volume/acme_srv.cfg
          sudo echo "eab_profiling: True" >> data/volume/acme_srv.cfg


      - name: "Reconfigure a2c "
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh restart $WEBSRV
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "EAB Profiling - Test enrollment"
        uses: ./.github/actions/wf_specific/dogtag_ca_handler/enroll_eabprofile

      - name: "Channel teardown"
        uses: ./.github/actions/channel_teardown
        with:
          DEPLOYMENT_TYPE: deb
          ARTIFACT_NAME: test-deb-${{ matrix.websrv }}-${{ matrix.mode }}.tar.gz
          WEBSRV: ${{ matrix.websrv }}
