name: Deployment Tests - Debian Packages
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
      run_id:
        description: 'Run ID of the producing workflow'
        required: true
        default: '0'
      sha:
        description: 'SHA of the commit to run the workflow on'
        required: true
        default: ''
      called_by_workflow:
        description: 'Name of the producing workflow'
        required: true
        default: 'manual-trigger'
      full_ref:
        description: 'Full git ref of the commit to run the workflow on'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch }}
  cancel-in-progress: true

permissions: {}

jobs:

  # ---------------------------------------------------------
  # Quick guard to validate incoming payload
  # ---------------------------------------------------------
  guard:
    permissions: {}
    uses: ./.github/workflows/_guard.yml
    with:
      sha: ${{ inputs.sha }}
      run_id: ${{ inputs.run_id }}
      branch: ${{ inputs.branch }}

  # ---------------------------------------------------------
  # Test DEB downloaded from the producer run
  # ---------------------------------------------------------
  test-deb:
    permissions:
      contents: read
      actions: write
    needs: guard
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      matrix:
        websrv: ['apache2', 'nginx']
        mode: ['wsgi', 'django']

    steps:
      - name: "Channel setup"
        uses: ./.github/actions/channel_deb_setup
        with:
          RUN_ID: ${{ inputs.run_id }}
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}
          DJANGO_DB: ${{ matrix.mode == 'django' && 'psql' || '' }}

      - name: "Parse NCLM configuration from JSON secret"
        uses: ./.github/actions/parse-json-secret
        with:
          json_secret: ${{ secrets.NCLM_CFG }}

      - name: "Retrieve Version from version.py"
        run: |
          echo TAG_NAME=$(cat acme2certifier/acme_srv/version.py | grep -i __version__ | head -n 1 | sed 's/__version__ = //g' | sed s/\"//g) >> $GITHUB_ENV

      - name: "Prepare acme_srv.cfg with openssl_ca_handler"
        uses: ./.github/actions/setup_openssl_cahandler

      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh install $WEBSRV -m $MODE
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "Test enrollment"
        uses: ./.github/actions/acme_clients

      - name: "Channel teardown"
        uses: ./.github/actions/channel_teardown
        with:
          DEPLOYMENT_TYPE: deb
          ARTIFACT_NAME: test-deb-${{ matrix.websrv }}-${{ matrix.mode }}.tar.gz
          WEBSRV: ${{ matrix.websrv }}
