name: Feature Tests - ARI
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
      run_id:
        description: 'Run ID of the producing workflow'
        required: true
        default: '0'
      sha:
        description: 'SHA of the commit to run the workflow on'
        required: true
        default: ''
      called_by_workflow:
        description: 'Name of the producing workflow'
        required: true
        default: 'manual-trigger'
      full_ref:
        description: 'Full git ref of the commit to run the workflow on'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch }}
  cancel-in-progress: true

permissions: {}

jobs:

  # ---------------------------------------------------------
  # Quick guard to validate incoming payload
  # ---------------------------------------------------------
  guard:
    permissions: {}
    uses: ./.github/workflows/_guard.yml
    with:
      sha: ${{ inputs.sha }}
      run_id: ${{ inputs.run_id }}
      branch: ${{ inputs.branch }}

  # ---------------------------------------------------------
  # Test container images downloaded from the producer run
  # ---------------------------------------------------------
  test-containers:
    permissions:
      contents: read
      actions: write
    needs: guard
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      matrix:
        websrv: ['apache2', 'nginx']
        dbhandler: ['wsgi', 'django']
    steps:

      - name: "Channel setup"
        uses: ./.github/actions/channel_container_setup
        with:
          RUN_ID: ${{ inputs.run_id }}
          WEB_SRV: ${{ matrix.websrv }}
          DB_HANDLER: ${{ matrix.dbhandler }}
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}

      - name: "Setup openssl ca_handler"
        uses: ./.github/actions/setup_openssl_cahandler
        with:
          VOLUME_DIR: "examples/Docker/data"

      - name: "Configure openssl ca_handler"
        run: |
          sudo chmod 777 examples/Docker/data/acme_srv.cfg
          sudo echo -e "\n\n[Renewalinfo]" >> examples/Docker/data/acme_srv.cfg
          sudo echo "renewal_force: True" >> examples/Docker/data/acme_srv.cfg
          cd examples/Docker/

      - name: "Bring up a2c container"
        uses: ./.github/actions/container_up
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}

      - name: "Test enrollment"
        uses: ./.github/actions/wf_specific/ari/enroll

      - name: "Check container configuration"
        uses: ./.github/actions/container_check
        with:
          DB_HANDLER: ${{ matrix.dbhandler }}
          WEB_SRV: ${{ matrix.websrv }}

      - name: "Channel teardown"
        uses: ./.github/actions/channel_teardown
        with:
          DEPLOYMENT_TYPE: container
          ARTIFACT_NAME: container-tests-${{ matrix.websrv }}-${{ matrix.dbhandler }}.tar.gz

  # ---------------------------------------------------------
  # Test RPMs (EL8 & EL9) downloaded from the producer run
  # ---------------------------------------------------------


  test-rpm:
    permissions:
      contents: read
      actions: write
    needs: guard
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      matrix:
        rhversion: [8, 9]
        mode: ['wsgi', 'django']

    steps:

      - name: "Channel setup"
        uses: ./.github/actions/channel_rpm_setup
        with:
          RUN_ID: ${{ inputs.run_id }}
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}
          RH_VERSION: ${{ matrix.rhversion }}
          JSON_SECRET: ${{ secrets.GH_CFG }}

      - name: "Prepare acme_srv.cfg with openssl_ca_handler"
        uses: ./.github/actions/setup_openssl_cahandler

      - name: "Prepare acme_srv.cfg with openssl_ca_handler (config)"
        run: |
          sudo chmod 777  data/volume/acme_srv.cfg
          sudo echo -e "\n\n[Renewalinfo]" >> data/volume/acme_srv.cfg
          sudo echo "renewal_force: True" >>  data/volume/acme_srv.cfg

      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-rpm.sh install -m $MODE
        env:
          MODE: ${{ matrix.mode }}

      - name: "Test enrollment"
        uses: ./.github/actions/wf_specific/ari/enroll
        with:
          CA_PATH: data/volume/acme_ca/

      - name: "Channel teardown"
        uses: ./.github/actions/channel_teardown
        with:
          DEPLOYMENT_TYPE: rpm
          ARTIFACT_NAME: test-rpm-rh${{ matrix.rhversion }}-${{ matrix.mode }}.tar.gz


  # ---------------------------------------------------------
  # Test DEB downloaded from the producer run
  # ---------------------------------------------------------


  test-deb:
    permissions:
      contents: read
      actions: write
    needs: guard
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      matrix:
        websrv: ['apache2', 'nginx']
        mode: ['wsgi', 'django']

    steps:
      - name: "Channel setup"
        uses: ./.github/actions/channel_deb_setup
        with:
          RUN_ID: ${{ inputs.run_id }}
          TOKEN: ${{ secrets.GH_WF_TOKEN }}
          REPO: ${{ github.repository }}
          DJANGO_DB: ${{ matrix.mode == 'django' && 'psql' || '' }}

      - name: "Prepare acme_srv.cfg with openssl_ca_handler"
        uses: ./.github/actions/setup_openssl_cahandler

      - name: "Prepare acme_srv.cfg with openssl_ca_handler (config)"
        run: |
          sudo chmod 777  data/volume/acme_srv.cfg
          sudo echo -e "\n\n[Renewalinfo]" >> data/volume/acme_srv.cfg
          sudo echo "renewal_force: True" >>  data/volume/acme_srv.cfg

      - name: "Execute install script"
        run: |
          docker exec acme-srv bash /tmp/acme2certifier/a2c-deb.sh install $WEBSRV -m $MODE
        env:
          WEBSRV: ${{ matrix.websrv }}
          MODE: ${{ matrix.mode }}

      - name: "Test enrollment"
        uses: ./.github/actions/wf_specific/ari/enroll
        with:
          CA_PATH: data/volume/acme_ca/

      - name: "Channel teardown"
        uses: ./.github/actions/channel_teardown
        with:
          DEPLOYMENT_TYPE: deb
          ARTIFACT_NAME: test-deb-${{ matrix.websrv }}-${{ matrix.mode }}.tar.gz
          WEBSRV: ${{ matrix.websrv }}
