name: Code quality - Markdown Check
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
      run_id:
        description: 'Run ID of the producing workflow'
        required: true
        default: '0'
      sha:
        description: 'SHA of the commit to run the workflow on'
        required: true
        default: ''
      called_by_workflow:
        description: 'Name of the producing workflow'
        required: true
        default: 'manual-trigger'
      full_ref:
        description: 'Full git ref of the commit to run the workflow on'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch }}
  cancel-in-progress: true

permissions: {}

jobs:
  # ---------------------------------------------------------
  # Quick guard to validate incoming payload
  # ---------------------------------------------------------
  guard:
    permissions: {}
    uses: ./.github/workflows/_guard.yml
    with:
      sha: ${{ inputs.sha }}
      run_id: ${{ inputs.run_id }}
      branch: ${{ inputs.branch }}

  markdown-link-check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: guard
    # Prevent workflows from running in forks
    if: github.repository == 'grindsa/acme2certifier'
    steps:

    - uses: actions/checkout@v7

    - name: Check markdown links
      uses: umbrelladocs/action-linkspector@568ec8d29fa92b31fd9ea5381e155c51e922af83 # v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        config_file: .linkspector.yml
        reporter: github-check
        filter_mode: nofilter
        fail_level: any
        show_stats: 'true'

    - name: Lint markdown root
      uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1
      with:
        args: '*.md'

    - name: Lint markdown docs
      uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1
      with:
        args: './docs/*.md'

    - name: Lint markdown docker
      uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1
      with:
        args: './examples/Docker/*.md'
